import { createButton, createCard, createSelectField, createStatePanel, createTextField } from '../../components/ui.js';
import { fail } from '../../services/ports/result.js';

export const TEAM_TABS=Object.freeze(['staff','roles','audit']);
function clone(v){return v==null?v:structuredClone(v);} function text(v){return String(v??'').trim();}
function can(actor,p){if(!actor)return false;if(actor.shopRole==='OWNER')return true;const a=Array.isArray(actor.permissions)?actor.permissions:[];return a.includes('*')||a.includes(p);}
function canAudit(actor){const roles=Array.isArray(actor?.roleCodes)?actor.roleCodes:[];return actor?.shopRole==='OWNER'||roles.includes('MANAGER');}
function ownerRow(row){return String(row?.role||'').toUpperCase()==='OWNER';}
function errorOf(result,msg){return result?.error||fail('NETWORK_ERROR',msg).error;}

export function createAdminTeamController({adminPort,actor}={}){
 if(!adminPort?.invoke)throw new TypeError('adminPort.invoke kerak.');const listeners=new Set();const staffAllowed=can(actor,'staff.manage'),auditAllowed=canAudit(actor);
 let state={allowed:staffAllowed||auditAllowed,permissions:{staff:staffAllowed,audit:auditAllowed},status:'idle',error:null,activeTab:staffAllowed?'staff':'audit',staff:[],pendingInvites:[],roles:[],permissionsCatalog:[],audit:[],auditPage:1,auditPageSize:30,auditTotal:0,auditTotalPages:1,filters:{staffSearch:'',staffStatus:'ALL',staffRole:'ALL',roleType:'ALL',audit:{search:'',action:'',entityType:'',adminTgId:'',dateFrom:'',dateTo:''}},selectedStaff:null,selectedRole:null,selectedAudit:null,roleDraft:null,inviteDraft:{telegramUserId:'',username:'',roleIds:[]},staffRoleDraft:null,busy:null,mutationError:null,mutationSuccess:null};
 const snap=()=>clone(state),emit=()=>listeners.forEach(f=>f(snap())),patch=p=>{state={...state,...p};emit();return snap();};
 async function loadStaff(){if(!staffAllowed)return patch({status:'permission',error:fail('FORBIDDEN','staff.manage huquqi kerak.').error});patch({status:'loading',error:null});const [r,s]=await Promise.all([adminPort.invoke('role_list',{}),adminPort.invoke('staff_list',{})]);if(!r?.ok||!s?.ok)return patch({status:'error',error:errorOf(!r?.ok?r:s,'Jamoa yuklanmadi.')});return patch({status:'ready',roles:clone(r.data.roles||[]),permissionsCatalog:clone(r.data.permissions||[]),staff:clone(s.data.staff||[]),pendingInvites:clone(s.data.pendingInvites||[]),error:null});}
 async function loadAudit(page=state.auditPage){if(!auditAllowed)return patch({status:'permission',error:fail('FORBIDDEN','Audit jurnaliga ruxsat yo‘q.').error});patch({status:'loading',error:null});const f=state.filters.audit;const payload={page,pageSize:state.auditPageSize};for(const k of ['search','action','entityType','adminTgId','dateFrom','dateTo'])if(text(f[k]))payload[k]=text(f[k]);const r=await adminPort.invoke('list_admin_audit_log',payload);if(!r?.ok)return patch({status:'error',error:errorOf(r,'Audit yuklanmadi.')});return patch({status:'ready',audit:clone(r.data.entries||[]),auditPage:r.data.page||page,auditPageSize:r.data.pageSize||state.auditPageSize,auditTotal:r.data.totalCount||0,auditTotalPages:r.data.totalPages||1,error:null});}
 async function load(){return state.activeTab==='audit'?loadAudit():loadStaff();}
 async function setTab(tab){if(!TEAM_TABS.includes(tab))return snap();if(tab==='audit'&&!auditAllowed)return snap();if((tab==='staff'||tab==='roles')&&!staffAllowed)return snap();patch({activeTab:tab,error:null});return load();}
 function setFilters(values={}){return patch({filters:{...state.filters,...clone(values)}});}function setAuditFilters(values={}){return patch({filters:{...state.filters,audit:{...state.filters.audit,...clone(values)}}});}
 function visibleStaff(){const q=text(state.filters.staffSearch).toLowerCase(),status=state.filters.staffStatus,role=state.filters.staffRole;return state.staff.filter(x=>(!q||`${x.name||''} ${x.username||''} ${x.tgId||''} ${x.phone||''}`.toLowerCase().includes(q))&&(status==='ALL'||x.status===status)&&(role==='ALL'||x.roles?.some(r=>String(r.id)===String(role))));}
 function visibleRoles(){return state.roles.filter(r=>state.filters.roleType==='ALL'||(state.filters.roleType==='SYSTEM'&&r.isSystem)||(state.filters.roleType==='CUSTOM'&&!r.isSystem));}
 function editRole(role=null){return patch({selectedRole:role?clone(role):null,roleDraft:role?{id:role.id,name:role.name||'',description:role.description||'',color:role.color||'',permissions:[...(role.permissions||[])]}:{id:null,name:'',description:'',color:'',permissions:[]},mutationError:null});}
 function updateRoleDraft(values){return patch({roleDraft:{...(state.roleDraft||{}),...clone(values)},mutationError:null});}
 function updateInviteDraft(values){return patch({inviteDraft:{...state.inviteDraft,...clone(values)},mutationError:null});}
 function editStaffRoles(row){if(ownerRow(row))return patch({mutationError:fail('FORBIDDEN','OWNER rollarini bu yerdan tahrirlab bo‘lmaydi.').error});const ids=(row?.roles||[]).map(r=>String(r.id)),primary=(row?.roles||[]).find(r=>r.isPrimary)?.id||ids[0]||null;return patch({selectedStaff:clone(row),staffRoleDraft:{telegramUserId:String(row.tgId),roleIds:ids,primaryRoleId:primary},mutationError:null});}
 function updateStaffRoleDraft(values){return patch({staffRoleDraft:{...(state.staffRoleDraft||{}),...clone(values)},mutationError:null});}
 async function mutate(action,payload,success,{reload=true}={}){patch({busy:action,mutationError:null,mutationSuccess:null});const r=await adminPort.invoke(action,payload);if(!r?.ok)return patch({busy:null,mutationError:errorOf(r,'Amal bajarilmadi.')});patch({busy:null,mutationSuccess:success});if(reload)await loadStaff();return snap();}
 async function saveRole(){const d=state.roleDraft;if(!d||!text(d.name))return patch({mutationError:fail('VALIDATION_ERROR','Rol nomini kiriting.').error});const payload={name:text(d.name),description:text(d.description)||null,color:text(d.color)||null,permissions:Array.isArray(d.permissions)?d.permissions:[]};const action=d.id?'role_update':'role_create';if(d.id)payload.id=d.id;const before=clone(d);patch({busy:action,mutationError:null,mutationSuccess:null});const r=await adminPort.invoke(action,payload);if(!r?.ok){state.roleDraft=before;return patch({busy:null,mutationError:errorOf(r,'Rol saqlanmadi.')});}patch({busy:null,mutationSuccess:'Rol saqlandi.',roleDraft:null,selectedRole:null});await loadStaff();return snap();}
 async function deleteRole(role,{force=false}={}){if(role?.isSystem)return patch({mutationError:fail('FORBIDDEN','Tizim rolini o‘chirib bo‘lmaydi.').error});if(Number(role?.usedCount||0)>0&&!force)return patch({mutationError:fail('CONFLICT',`Bu rol ${Number(role.usedCount)} ta xodimda ishlatilmoqda. Tasdiqlasangiz force bilan o‘chiring.`).error});return mutate('role_delete',{id:role?.id,force:!!force},'Rol o‘chirildi.');}
 async function invite(){const d=state.inviteDraft;if(!/^\d+$/.test(text(d.telegramUserId))||!(d.roleIds||[]).length)return patch({mutationError:fail('VALIDATION_ERROR','Telegram ID va kamida bitta rol kerak.').error});const before=clone(d);patch({busy:'staff_invite',mutationError:null,mutationSuccess:null});const r=await adminPort.invoke('staff_invite',{telegramUserId:text(d.telegramUserId),username:text(d.username)||null,roleIds:[...(d.roleIds||[])]});if(!r?.ok){state.inviteDraft=before;return patch({busy:null,mutationError:errorOf(r,'Taklif yuborilmadi.')});}patch({busy:null,mutationSuccess:'Taklif yuborildi.',inviteDraft:{telegramUserId:'',username:'',roleIds:[]}});await loadStaff();return snap();}
 async function cancelInvite(id){return mutate('staff_cancel_invite',{inviteId:id},'Taklif bekor qilindi.');}
 async function saveStaffRoles(){const d=state.staffRoleDraft;if(!d||!(d.roleIds||[]).length)return patch({mutationError:fail('VALIDATION_ERROR','Kamida bitta rol tanlang.').error});const row=state.staff.find(x=>String(x.tgId)===String(d.telegramUserId));if(ownerRow(row))return patch({mutationError:fail('FORBIDDEN','OWNER rollarini almashtirib bo‘lmaydi.').error});const before=clone(d);patch({busy:'staff_update_roles',mutationError:null,mutationSuccess:null});const r=await adminPort.invoke('staff_update_roles',{telegramUserId:d.telegramUserId,roleIds:[...d.roleIds],primaryRoleId:d.primaryRoleId});if(!r?.ok){state.staffRoleDraft=before;return patch({busy:null,mutationError:errorOf(r,'Rollar saqlanmadi.')});}patch({busy:null,mutationSuccess:'Xodim rollari saqlandi.',staffRoleDraft:null,selectedStaff:null});await loadStaff();return snap();}
 async function setBlocked(row,blocked){if(ownerRow(row))return patch({mutationError:fail('FORBIDDEN','OWNER bloklanmaydi.').error});return mutate('staff_set_blocked',{telegramUserId:String(row.tgId),blocked:!!blocked},blocked?'Xodim bloklandi.':'Xodim blokdan chiqarildi.');}
 async function removeStaff(row){if(ownerRow(row))return patch({mutationError:fail('FORBIDDEN','OWNER jamoa tarkibidan olib tashlanmaydi.').error});return mutate('staff_remove',{telegramUserId:String(row.tgId)},'Xodim olib tashlandi.');}
 return Object.freeze({getState:snap,subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);},load,loadStaff,loadAudit,setTab,setFilters,setAuditFilters,visibleStaff,visibleRoles,editRole,updateRoleDraft,updateInviteDraft,editStaffRoles,updateStaffRoleDraft,saveRole,deleteRole,invite,cancelInvite,saveStaffRoles,setBlocked,removeStaff});
}

function pill(doc,label){const p=doc.createElement('span');p.className='uw-chip';p.textContent=String(label);return p;}
function rowsTable(doc,headers,rows,onClick){const w=doc.createElement('div');w.className='uw-table-wrap';const t=doc.createElement('table');t.className='uw-data-table';const h=doc.createElement('tr');headers.forEach(x=>{const th=doc.createElement('th');th.textContent=x.label;h.append(th);});const thead=doc.createElement('thead');thead.append(h);const tbody=doc.createElement('tbody');for(const row of rows){const tr=doc.createElement('tr');if(onClick){tr.tabIndex=0;tr.addEventListener('click',()=>onClick(row));}for(const x of headers){const td=doc.createElement('td');const v=typeof x.value==='function'?x.value(row):row[x.value];td.textContent=String(v??'—');tr.append(td);}tbody.append(tr);}t.append(thead,tbody);w.append(t);return w;}

export function renderAdminTeam({controller,documentRef=globalThis.document}={}){if(!controller?.getState)throw new TypeError('controller kerak.');const doc=documentRef,root=doc.createElement('section');root.className='uw-feature uw-admin-team';const render=()=>{const s=controller.getState();root.replaceChildren();if(!s.allowed){root.append(createStatePanel({kind:'permission',title:'Jamoaga ruxsat yo‘q',message:'staff.manage yoki audit uchun manager/owner huquqi kerak.'},doc));return;}const tabs=doc.createElement('div');tabs.className='uw-tab-row';if(s.permissions.staff){for(const [id,label] of [['staff','Xodimlar'],['roles','Rollar']])tabs.append(createButton({label,variant:s.activeTab===id?'primary':'ghost',size:'sm',onClick:()=>controller.setTab(id)},doc));}if(s.permissions.audit)tabs.append(createButton({label:'Amallar jurnali',variant:s.activeTab==='audit'?'primary':'ghost',size:'sm',onClick:()=>controller.setTab('audit')},doc));root.append(tabs);if(s.status==='loading'){root.append(createStatePanel({kind:'loading',title:'Yuklanmoqda…',message:'Jamoa ma’lumotlari olinmoqda.'},doc));return;}if(s.status==='error'||s.status==='permission'){root.append(createStatePanel({kind:s.status==='permission'?'permission':'error',title:s.status==='permission'?'Ruxsat yo‘q':'Ma’lumot yuklanmadi',message:s.error?.message||'Xato',actionLabel:s.status==='error'?'Qayta urinish':'',onAction:()=>controller.load()},doc));return;}
 if(s.activeTab==='staff'){const tools=doc.createElement('div');tools.className='uw-inline-fields';const q=createTextField({label:'Qidiruv',value:s.filters.staffSearch},doc);q.input.addEventListener('input',()=>{controller.setFilters({staffSearch:q.input.value});});const st=createSelectField({label:'Status',value:s.filters.staffStatus,options:['ALL','ACTIVE','DISABLED'].map(v=>({value:v,label:v}))},doc);st.select.addEventListener('change',()=>controller.setFilters({staffStatus:st.select.value}));const role=createSelectField({label:'Rol',value:s.filters.staffRole,options:[{value:'ALL',label:'Barcha rollar'},...s.roles.map(r=>({value:r.id,label:r.name}))]},doc);role.select.addEventListener('change',()=>controller.setFilters({staffRole:role.select.value}));tools.append(q.element,st.element,role.element);root.append(tools,rowsTable(doc,[{label:'Xodim',value:r=>r.name||r.username||r.tgId},{label:'Telegram ID',value:'tgId'},{label:'Status',value:'status'},{label:'Rollar',value:r=>(r.roles||[]).map(x=>x.name).join(', ')||r.role}],controller.visibleStaff(),row=>{controller.editStaffRoles(row);render();}));
 const body=doc.createElement('div');body.className='uw-inline-fields';const inv=createCard({title:'Xodim taklif qilish',description:'Telegram ID va kamida bitta rol tanlang.',body},doc);const id=createTextField({label:'Telegram ID',value:s.inviteDraft.telegramUserId},doc);id.input.addEventListener('input',()=>controller.updateInviteDraft({telegramUserId:id.input.value}));const un=createTextField({label:'Username (ixtiyoriy)',value:s.inviteDraft.username},doc);un.input.addEventListener('input',()=>controller.updateInviteDraft({username:un.input.value}));const rs=createSelectField({label:'Rol',value:s.inviteDraft.roleIds?.[0]||'',options:[{value:'',label:'Rolni tanlang'},...s.roles.map(r=>({value:r.id,label:r.name}))]},doc);rs.select.addEventListener('change',()=>controller.updateInviteDraft({roleIds:rs.select.value?[rs.select.value]:[]}));body.append(id.element,un.element,rs.element,createButton({label:'Taklif yuborish',busy:s.busy==='staff_invite',onClick:()=>controller.invite()},doc));root.append(inv);if(s.pendingInvites.length)root.append(rowsTable(doc,[{label:'Kutilayotgan ID',value:'tgId'},{label:'Rollar',value:r=>(r.roleIds||[]).length},{label:'Muddati',value:'expiresAt'}],s.pendingInvites));
 if(s.staffRoleDraft){const row=s.staff.find(x=>String(x.tgId)===String(s.staffRoleDraft.telegramUserId));const panelBody=doc.createElement('div');panelBody.className='uw-stack';const panel=createCard({title:`Rollar — ${row?.name||row?.tgId}`,description:ownerRow(row)?'OWNER himoyalangan.':'Xodim rollarini server orqali saqlash.',body:panelBody},doc);if(!ownerRow(row)){const select=createSelectField({label:'Asosiy rol',value:s.staffRoleDraft.primaryRoleId||'',options:s.roles.map(r=>({value:r.id,label:r.name}))},doc);select.select.addEventListener('change',()=>controller.updateStaffRoleDraft({roleIds:[select.select.value],primaryRoleId:select.select.value}));panelBody.append(select.element,createButton({label:'Rollarni saqlash',busy:s.busy==='staff_update_roles',onClick:()=>controller.saveStaffRoles()},doc),createButton({label:row?.status==='DISABLED'?'Blokdan chiqarish':'Bloklash',variant:'secondary',onClick:()=>controller.setBlocked(row,row?.status!=='DISABLED')},doc),createButton({label:'Olib tashlash',variant:'danger',onClick:()=>controller.removeStaff(row)},doc));}root.append(panel);}}
 else if(s.activeTab==='roles'){const filter=createSelectField({label:'Rol turi',value:s.filters.roleType,options:[{value:'ALL',label:'Barchasi'},{value:'SYSTEM',label:'Tizim'},{value:'CUSTOM',label:'Custom'}]},doc);filter.select.addEventListener('change',()=>controller.setFilters({roleType:filter.select.value}));root.append(filter.element,rowsTable(doc,[{label:'Rol',value:'name'},{label:'Turi',value:r=>r.isSystem?'Tizim':'Custom'},{label:'Xodim',value:'usedCount'},{label:'Permission',value:r=>(r.permissions||[]).length}],controller.visibleRoles(),r=>{controller.editRole(r);render();}),createButton({label:'+ Yangi rol',onClick:()=>{controller.editRole();render();}},doc));if(s.roleDraft){const d=s.roleDraft,body=doc.createElement('div');body.className='uw-stack';const card=createCard({title:d.id?'Rolni tahrirlash':'Yangi rol',body},doc);const n=createTextField({label:'Nomi',value:d.name},doc);n.input.addEventListener('input',()=>controller.updateRoleDraft({name:n.input.value}));const de=createTextField({label:'Izoh',value:d.description},doc);de.input.addEventListener('input',()=>controller.updateRoleDraft({description:de.input.value}));const co=createTextField({label:'Rang',value:d.color,placeholder:'#2563eb'},doc);co.input.addEventListener('input',()=>controller.updateRoleDraft({color:co.input.value}));const ps=createSelectField({label:'Permission',value:d.permissions?.[0]||'',options:[{value:'',label:'Permission tanlang'},...s.permissionsCatalog.map(p=>({value:p,label:p}))]},doc);ps.select.addEventListener('change',()=>controller.updateRoleDraft({permissions:ps.select.value?[ps.select.value]:[]}));body.append(n.element,de.element,co.element,ps.element,createButton({label:'Saqlash',busy:s.busy==='role_create'||s.busy==='role_update',onClick:()=>controller.saveRole()},doc));if(d.id&&!s.selectedRole?.isSystem)body.append(createButton({label:'O‘chirish',variant:'danger',onClick:()=>controller.deleteRole(s.selectedRole,{force:false})},doc));root.append(card);}}
 else{const f=doc.createElement('div');f.className='uw-inline-fields';const q=createTextField({label:'Qidiruv',value:s.filters.audit.search},doc);q.input.addEventListener('change',()=>{controller.setAuditFilters({search:q.input.value});controller.loadAudit(1);});const a=createTextField({label:'Action',value:s.filters.audit.action},doc);a.input.addEventListener('change',()=>{controller.setAuditFilters({action:a.input.value});controller.loadAudit(1);});f.append(q.element,a.element);root.append(f,rowsTable(doc,[{label:'Vaqt',value:'createdAt'},{label:'Admin',value:'adminName'},{label:'Action',value:'action'},{label:'Obyekt',value:r=>`${r.entityType||''} ${r.entityId||''}`.trim()}],s.audit));}
 if(s.mutationError)root.append(createStatePanel({kind:'error',title:'Amal bajarilmadi',message:s.mutationError.message},doc));if(s.mutationSuccess){const p=doc.createElement('p');p.className='uw-success-note';p.textContent=s.mutationSuccess;root.append(p);}};render();const u=controller.subscribe(render);return{element:root,destroy:u};}
