import { createButton, createStatePanel } from '../../components/ui.js';

function getDocument(documentRef) {
  const doc = documentRef || globalThis.document;
  if (!doc?.createElement) throw new Error('document kerak');
  return doc;
}
function el(doc, tag, className = '', text = null) {
  const n = doc.createElement(tag);
  if (className) n.className = className;
  if (text != null) n.textContent = String(text);
  return n;
}
function nameControl(control, label) {
  if (control?.setAttribute && label) control.setAttribute('aria-label', String(label));
  return control;
}
function list(value) { return Array.isArray(value) ? value.filter(Boolean) : []; }
function text(value, fallback = '—') { const s = String(value ?? '').trim(); return s || fallback; }
function money(value) { return `${new Intl.NumberFormat('uz-UZ').format(Number(value || 0))} so‘m`; }
function date(value) { if (!value) return '—'; const d = new Date(value); return Number.isNaN(d.getTime()) ? '—' : new Intl.DateTimeFormat('uz-UZ', { day:'2-digit', month:'short', year:'numeric' }).format(d); }
function dateTime(value) { if (!value) return '—'; const d = new Date(value); return Number.isNaN(d.getTime()) ? '—' : new Intl.DateTimeFormat('uz-UZ', { day:'2-digit', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' }).format(d); }
function statusTone(value) { const s=String(value||'').toUpperCase(); if(['ACTIVE','APPROVED','ANSWERED'].includes(s)) return 'success'; if(['NEW','FROZEN','PROVISIONING','PENDING'].includes(s)) return 'warning'; if(['TERMINATED','REJECTED','ERROR','CLOSED'].includes(s)) return 'danger'; return 'neutral'; }
function statusLabel(value) { const s=String(value||'').toUpperCase(); return ({ACTIVE:'Faol',FROZEN:'Muzlatilgan',TERMINATED:"O‘chirilgan",PROVISIONING:'Sozlanmoqda',NEW:'Yangi',APPROVED:'Tasdiqlangan',REJECTED:'Rad etilgan',OPEN:'Ochiq',ANSWERED:'Javob berilgan',CLOSED:'Yopilgan'})[s] || s || 'Noma’lum'; }
function badge(doc, label, tone='neutral') { return el(doc, 'span', `uw-platform-badge uw-platform-badge--${tone}`, label); }
function safeUrl(value) { try { const u = new URL(String(value||'')); return ['https:','http:'].includes(u.protocol) ? u.href : ''; } catch { return ''; } }
function createStore(initial) {
  let state = Object.freeze(initial); const listeners = new Set();
  return { get:()=>state, set:(patch)=>{ state=Object.freeze({...state,...patch}); for(const fn of listeners) fn(state); return state; }, subscribe:(fn)=>{listeners.add(fn); return ()=>listeners.delete(fn);} };
}
function localFail(message='Bu amal faqat platforma Super Admin uchun.') { return { ok:false, error:{ code:'FORBIDDEN', message } }; }
function normalizeShop(row) { if(!row?.id) return null; return {...row,id:String(row.id),status:String(row.status||'UNKNOWN').toUpperCase()}; }
function normalizeRequest(row) { if(!row?.id) return null; return {...row,id:String(row.id),status:String(row.status||'UNKNOWN').toUpperCase(),tariffPrice:Number(row.tariffPrice||0)}; }
function normalizeTariff(row) { if(!row?.id)return null; return {...row,id:String(row.id),price:Number(row.price||0),productLimit:row.productLimit==null?null:Number(row.productLimit),features:list(row.features).map(String)}; }

export function createPlatformAdminController({ platformPort, authPort = null } = {}) {
  if (!platformPort?.invoke) throw new TypeError('platformPort kerak');
  const store = createStore({
    status:'idle', error:null, actor:null, isSuperAdmin:false, notice:null, mutationStatus:null,
    dashboardStatus:'idle', dashboard:null,
    shopsStatus:'idle', shops:[], selectedShopId:null, shopHistory:[], shopActions:[], shopQuery:'', shopStatusFilter:'ALL',
    requestsStatus:'idle', requests:[], requestStatusFilter:'ALL', selectedRequestId:null, requestHistory:[], requestDetail:null,
    supportStatus:'idle', tickets:[], supportStatusFilter:'OPEN', selectedTicketId:null, messages:[],
    tariffsStatus:'idle', tariffs:[],
    analyticsStatus:'idle', analytics:null, analyticsPeriod:'30d',
    settingsStatus:'idle', lifecycleSettings:null, paymentInfo:null, paymentMethods:[], notificationTemplates:[],
  });
  let shopView=0, requestView=0, ticketView=0;
  const invoke=(action,payload={})=>platformPort.invoke(action,payload);
  const setNotice=(kind,message)=>store.set({notice:message?{kind,message}:null});
  const canAdmin=()=>store.get().status==='ready' && store.get().isSuperAdmin===true;
  async function requireAdminInvoke(action,payload={}) { if(!canAdmin()) return localFail(); return invoke(action,payload); }

  async function load() {
    store.set({status:'loading',error:null});
    const r=await invoke('platform_boot',{});
    if(!r.ok){store.set({status:'error',error:r.error||{message:'Platforma yuklanmadi.'}});return r;}
    const isSuperAdmin=r.data?.isSuperAdmin===true || r.data?.platformActor?.platformRole==='SUPER_ADMIN';
    if(!isSuperAdmin){store.set({status:'forbidden',error:null,actor:r.data?.platformActor||null,isSuperAdmin:false});return localFail();}
    store.set({status:'ready',error:null,actor:r.data?.platformActor||null,isSuperAdmin:true});
    return r;
  }
  async function loadDashboard(){if(!canAdmin())return localFail();store.set({dashboardStatus:'loading'});const r=await requireAdminInvoke('platform_admin_dashboard_summary',{});store.set(r.ok?{dashboardStatus:'ready',dashboard:r.data}:{dashboardStatus:'error'});return r;}
  async function loadShops({shopId=null}={}){if(!canAdmin())return localFail();store.set({shopsStatus:'loading'});const r=await requireAdminInvoke('platform_list_shops',{});if(!r.ok){store.set({shopsStatus:'error'});return r;}const shops=list(r.data?.shops).map(normalizeShop).filter(Boolean);const current=shopId?String(shopId):store.get().selectedShopId;const selected=shops.some(s=>s.id===current)?current:(shops[0]?.id||null);store.set({shopsStatus:'ready',shops,selectedShopId:selected});if(shopId)await loadShopDetail(shopId,{skipList:true});return r;}
  async function loadShopDetail(shopId,{skipList=false}={}){const view=++shopView;const id=String(shopId||'');if(!id)return {ok:false,error:{code:'VALIDATION_ERROR',message:"Do‘kon tanlanmagan."}};if(!canAdmin())return localFail();if(!skipList&&!store.get().shops.length){const lr=await loadShops();if(!lr.ok)return lr;}if(view!==shopView)return {ok:false,error:{code:'CONFLICT',message:'Selection changed',retryable:false}};store.set({selectedShopId:id,shopHistory:[],shopActions:[]});const [history,actions]=await Promise.all([requireAdminInvoke('platform_list_subscription_history',{shopId:id}),requireAdminInvoke('platform_list_shop_admin_actions',{shopId:id})]);if(view!==shopView)return {ok:false,error:{code:'CONFLICT',message:'Selection changed',retryable:false}};store.set({shopHistory:history.ok?list(history.data?.history):[],shopActions:actions.ok?list(actions.data?.actions):[]});return history.ok||actions.ok?{ok:true,data:{}}:(history.ok?actions:history);}
  async function loadRequests({status=store.get().requestStatusFilter,requestId=null}={}){if(!canAdmin())return localFail();const normalized=['NEW','APPROVED','REJECTED'].includes(String(status))?String(status):'ALL';store.set({requestsStatus:'loading',requestStatusFilter:normalized});const r=await requireAdminInvoke('platform_list_subscription_requests',normalized==='ALL'?{}:{status:normalized});if(!r.ok){store.set({requestsStatus:'error'});return r;}const requests=list(r.data?.requests).map(normalizeRequest).filter(Boolean);store.set({requestsStatus:'ready',requests});if(requestId)await loadRequestDetail(requestId);return r;}
  async function loadRequestDetail(requestId){const view=++requestView;const id=String(requestId||'');if(!id)return {ok:false,error:{code:'VALIDATION_ERROR',message:'Ariza tanlanmagan.'}};if(!canAdmin())return localFail();store.set({selectedRequestId:id,requestHistory:[],requestDetail:null});const r=await requireAdminInvoke('platform_get_subscription_request_history',{requestId:id});if(view!==requestView)return r;if(r.ok)store.set({requestDetail:normalizeRequest(r.data?.request),requestHistory:list(r.data?.history)});return r;}
  async function loadSupport({status=store.get().supportStatusFilter,ticketId=null}={}){if(!canAdmin())return localFail();const normalized=['OPEN','ANSWERED','CLOSED'].includes(String(status))?String(status):'ALL';store.set({supportStatus:'loading',supportStatusFilter:normalized});const r=await requireAdminInvoke('platform_admin_list_support_tickets',normalized==='ALL'?{}:{status:normalized});if(!r.ok){store.set({supportStatus:'error'});return r;}store.set({supportStatus:'ready',tickets:list(r.data?.tickets)});if(ticketId)await openTicket(ticketId);return r;}
  async function openTicket(ticketId){const view=++ticketView;const id=Number(ticketId);if(!Number.isInteger(id)||id<=0)return {ok:false,error:{code:'VALIDATION_ERROR',message:'Murojaat tanlanmagan.'}};if(!canAdmin())return localFail();store.set({selectedTicketId:id,messages:[]});const r=await requireAdminInvoke('platform_get_support_messages',{ticketId:id});if(view!==ticketView)return r;if(r.ok)store.set({messages:list(r.data?.messages)});return r;}
  async function loadTariffs(){if(!canAdmin())return localFail();store.set({tariffsStatus:'loading'});const r=await requireAdminInvoke('platform_admin_list_tariffs',{});store.set(r.ok?{tariffsStatus:'ready',tariffs:list(r.data?.tariffs).map(normalizeTariff).filter(Boolean)}:{tariffsStatus:'error'});return r;}
  async function loadAnalytics(period=store.get().analyticsPeriod){if(!canAdmin())return localFail();const p=['7d','30d','90d','all'].includes(String(period))?String(period):'30d';store.set({analyticsStatus:'loading',analyticsPeriod:p});const r=await requireAdminInvoke('platform_admin_analytics_summary',{period:p});store.set(r.ok?{analyticsStatus:'ready',analytics:r.data}:{analyticsStatus:'error'});return r;}
  async function loadSettings(){if(!canAdmin())return localFail();store.set({settingsStatus:'loading'});const [life,card,methods,templates]=await Promise.all([requireAdminInvoke('platform_get_lifecycle_settings',{}),requireAdminInvoke('platform_get_payment_info',{}),requireAdminInvoke('platform_admin_list_payment_methods',{}),requireAdminInvoke('platform_admin_list_notification_templates',{})]);const okAny=life.ok||card.ok||methods.ok||templates.ok;store.set({settingsStatus:okAny?'ready':'error',lifecycleSettings:life.ok?life.data?.settings:null,paymentInfo:card.ok?card.data:null,paymentMethods:methods.ok?list(methods.data?.methods):[],notificationTemplates:templates.ok?list(templates.data?.templates):[]});return okAny?{ok:true,data:{}}:(life.ok?card:life);}
  async function loadSection(section,params={}){if(store.get().status==='idle'||store.get().status==='error')await load();if(!canAdmin())return localFail();if(section==='shops')return loadShops({shopId:params.shopId||null});if(section==='requests')return loadRequests({requestId:params.requestId||null});if(section==='support')return loadSupport({ticketId:params.ticketId||null});if(section==='tariffs')return loadTariffs();if(section==='analytics')return loadAnalytics();if(section==='settings')return loadSettings();return loadDashboard();}
  async function mutate(key,action,payload,onSuccess,message){if(!canAdmin())return localFail();store.set({mutationStatus:key});try{const r=await requireAdminInvoke(action,payload);if(r.ok){setNotice('success',message||'Amal bajarildi.');if(onSuccess)await onSuccess(r);}else setNotice('error',r.error?.message||'Amal bajarilmadi.');return r;}finally{store.set({mutationStatus:null});}}
  const refreshShop=async(id)=>{await loadShops();if(id)await loadShopDetail(id,{skipList:true});};
  function setShopQuery(value){store.set({shopQuery:String(value||'')});}
  function setShopStatusFilter(value){store.set({shopStatusFilter:['ALL','ACTIVE','FROZEN','PROVISIONING','TERMINATED'].includes(String(value))?String(value):'ALL'});}
  async function setIntegrationAccess(shopId,kind,enabled){const map={billz:'platform_set_billz_access',click:'platform_set_click_access',payme:'platform_set_payme_access',uzum:'platform_set_uzum_access'};const action=map[String(kind||'').toLowerCase()];if(!action)return {ok:false,error:{code:'VALIDATION_ERROR',message:'Integratsiya turi noto‘g‘ri.'}};return mutate(`access:${kind}`,action,{shopId:String(shopId),enabled:enabled===true},()=>refreshShop(shopId),'Integratsiya ruxsati yangilandi.');}
  async function grantDays(shopId,days,reason){return mutate('grant-days','platform_grant_subscription_days',{shopId:String(shopId),days:Number(days),reason:String(reason||'')},()=>refreshShop(shopId),'Obuna muddati yangilandi.');}
  async function freezeShop(shopId,reason){return mutate('freeze','platform_freeze_shop',{shopId:String(shopId),reason:String(reason||'')},()=>refreshShop(shopId),"Do‘kon muzlatildi.");}
  async function reactivateShop(shopId){return mutate('reactivate','platform_reactivate_shop',{shopId:String(shopId)},()=>refreshShop(shopId),"Do‘kon qayta faollashtirildi.");}
  async function extendFrozenGrace(shopId,days,reason){return mutate('extend-grace','platform_extend_frozen_grace',{shopId:String(shopId),days:Number(days),reason:String(reason||'')},()=>refreshShop(shopId),'Saqlash muddati uzaytirildi.');}
  async function terminateShop(shopId,reason){return mutate('terminate','platform_terminate_shop',{shopId:String(shopId),reason:String(reason||'')},async(r)=>{await loadShops();store.set({selectedShopId:null,shopHistory:[],shopActions:[]});if(r.data?.backupDownloadUrl)setNotice('warning',"Do‘kon o‘chirildi. Backup havolasi vaqtinchalik — darhol saqlang.");},"Do‘kon o‘chirildi.");}
  async function approveRequest(requestId){return mutate('approve-request','platform_approve_subscription_request',{requestId:String(requestId)},async()=>{await loadRequests({status:store.get().requestStatusFilter,requestId});},'To‘lov tasdiqlandi.');}
  async function rejectRequest(requestId,reason){return mutate('reject-request','platform_reject_subscription_request',{requestId:String(requestId),reason:String(reason||'')},async()=>{await loadRequests({status:store.get().requestStatusFilter,requestId});},'Ariza rad etildi.');}
  async function provisionShop(requestId,botToken){const secret=String(botToken||'').trim();if(!secret)return {ok:false,error:{code:'VALIDATION_ERROR',message:'Bot token kerak.'}};return mutate('provision','platform_provision_shop_from_request',{requestId:String(requestId),botToken:secret},async()=>{await Promise.all([loadRequests({status:store.get().requestStatusFilter,requestId}),loadShops()]);},"Do‘kon yaratish oqimi bajarildi.");}
  async function getReceiptUrl(requestId){return requireAdminInvoke('platform_get_subscription_receipt_url',{requestId:String(requestId)});}
  async function getBotPhotoUrl(requestId){return requireAdminInvoke('platform_get_bot_photo_url',{requestId:String(requestId)});}
  async function sendSupportMessage(ticketId,body){const value=String(body||'').trim();if(!value)return {ok:false,error:{code:'VALIDATION_ERROR',message:'Xabarni kiriting.'}};return mutate('support-send','platform_send_support_message',{ticketId:Number(ticketId),body:value},async()=>{await openTicket(ticketId);await loadSupport({status:store.get().supportStatusFilter});store.set({selectedTicketId:Number(ticketId)});},'Javob yuborildi.');}
  async function closeSupportTicket(ticketId){return mutate('support-close','platform_close_support_ticket',{ticketId:Number(ticketId)},async()=>{await loadSupport({status:store.get().supportStatusFilter});store.set({selectedTicketId:null,messages:[]});},'Murojaat yopildi.');}
  async function saveTariff(payload){const clean={...payload,id:payload?.id?String(payload.id):undefined,name:String(payload?.name||'').trim(),price:Number(payload?.price),productLimit:payload?.productLimit===''?null:payload?.productLimit==null?null:Number(payload.productLimit),sortOrder:Number(payload?.sortOrder||0),isActive:payload?.isActive!==false,isPopular:payload?.isPopular===true,features:list(payload?.features).map(x=>String(x).trim()).filter(Boolean)};return mutate('tariff','platform_upsert_tariff',clean,()=>loadTariffs(),'Tarif saqlandi.');}
  async function saveLifecycleSettings(payload){return mutate('lifecycle','platform_update_lifecycle_settings',payload,()=>loadSettings(),'Lifecycle sozlamalari saqlandi.');}
  async function savePaymentInfo(payload){return mutate('payment-card','platform_set_payment_info',{cardNumber:String(payload?.cardNumber||''),cardHolder:String(payload?.cardHolder||''),isActive:payload?.isActive!==false},()=>loadSettings(),'To‘lov kartasi saqlandi.');}
  async function savePaymentMethod(payload){return mutate('payment-method','platform_upsert_payment_method',{...payload,id:payload?.id?String(payload.id):undefined,methodType:String(payload?.methodType||'').toUpperCase(),displayName:String(payload?.displayName||''),paymentUrl:String(payload?.paymentUrl||''),isActive:payload?.isActive!==false,sortOrder:Number(payload?.sortOrder||0)},()=>loadSettings(),'To‘lov usuli saqlandi.');}
  async function saveNotificationTemplate(payload){return mutate('notification','platform_update_notification_template',{...payload,type:String(payload?.type||''),body:String(payload?.body||''),imageUrl:String(payload?.imageUrl||'')||null,isActive:payload?.isActive!==false},()=>loadSettings(),'Xabar shabloni saqlandi.');}
  async function sendTestNotification(type){return mutate('notification-test','platform_send_test_notification',{type:String(type||'')},null,'Sinov xabari Super Admin akkauntiga yuborildi.');}
  async function setupPlatformBot(){return mutate('platform-setup','platform_setup',{},null,'Platform bot konfiguratsiyasi bajarildi.');}
  async function signOut(){if(!authPort?.signOut)return {ok:false,error:{code:'UNAVAILABLE',message:'Chiqish mavjud emas.'}};const r=await authPort.signOut();if(r.ok)store.set({status:'idle',actor:null,isSuperAdmin:false});return r;}

  return Object.freeze({
    getState:store.get,subscribe:store.subscribe,load,loadSection,loadDashboard,loadShops,loadShopDetail,loadRequests,loadRequestDetail,loadSupport,openTicket,loadTariffs,loadAnalytics,loadSettings,
    setShopQuery,setShopStatusFilter,setIntegrationAccess,grantDays,freezeShop,reactivateShop,extendFrozenGrace,terminateShop,approveRequest,rejectRequest,provisionShop,getReceiptUrl,getBotPhotoUrl,
    sendSupportMessage,closeSupportTicket,saveTariff,saveLifecycleSettings,savePaymentInfo,savePaymentMethod,saveNotificationTemplate,sendTestNotification,setupPlatformBot,signOut,setNotice,
  });
}

const ADMIN_NAV=[
  ['overview','Umumiy','/platform/admin'],['shops',"Do‘konlar",'/platform/admin/shops'],['requests','Arizalar','/platform/admin/requests'],['support','Support','/platform/admin/support'],['tariffs','Tariflar','/platform/admin/tariffs'],['analytics','Analitika','/platform/admin/analytics'],['settings','Sozlamalar','/platform/admin/settings'],
];
function adminHeader(doc,state,{onNavigate,onLogout}){const h=el(doc,'header','uw-platform-admin__header');const brand=el(doc,'button','uw-platform-admin__brand');brand.type='button';brand.append(el(doc,'span','uw-platform-admin__mark','U'),el(doc,'span','','UStorE'),badge(doc,'SUPER ADMIN','warning'));brand.addEventListener('click',()=>onNavigate?.('/platform/admin'));const right=el(doc,'div','uw-platform-admin__header-actions');const who=el(doc,'div','uw-platform-actor');who.append(el(doc,'strong','',state.actor?.displayName||'Super Admin'),el(doc,'small','','Markaziy platforma vakolati'));right.append(createButton({label:'Foydalanuvchi portaliga',variant:'ghost',size:'sm',onClick:()=>onNavigate?.('/platform/app')},doc),who,createButton({label:'Chiqish',variant:'ghost',size:'sm',onClick:onLogout},doc));h.append(brand,right);return h;}
function adminNav(doc,active,onNavigate){const nav=el(doc,'nav','uw-platform-admin__nav');nav.setAttribute('aria-label','Super Admin bo‘limlari');for(const [id,label,href] of ADMIN_NAV){const a=el(doc,'a',id===active?'is-active':'',label);a.href=href;a.addEventListener('click',(e)=>{e.preventDefault?.();onNavigate?.(href);});nav.append(a);}return nav;}
function pageHead(doc,title,subtitle,action=null){const row=el(doc,'div','uw-platform-page-head');const copy=el(doc,'div');copy.append(el(doc,'h1','',title),el(doc,'p','',subtitle));row.append(copy);if(action)row.append(action);return row;}
function inlineState(doc,status,{loading='Yuklanmoqda…',empty='',error='Ma’lumot yuklanmadi.',retry=null}={}){if(status==='loading'||status==='idle')return createStatePanel({kind:'loading',title:loading,message:'Serverdan haqiqiy ma’lumot olinmoqda.'},doc);if(status==='error')return createStatePanel({kind:'error',title:error,message:'Server so‘rovi bajarilmadi.',actionLabel:retry?'Qayta urinish':'',onAction:retry||undefined},doc);if(status==='ready'&&empty)return createStatePanel({kind:'empty',title:empty,message:'Hozircha yozuv yo‘q.'},doc);return null;}
function stat(doc,label,value,meta=''){const n=el(doc,'article','uw-platform-stat');n.append(el(doc,'small','',label),el(doc,'strong','',value));if(meta)n.append(el(doc,'span','',meta));return n;}
function openExternal(url){const safe=safeUrl(url);if(safe)globalThis.open?.(safe,'_blank','noopener,noreferrer');}

function dashboardView(doc,state,onNavigate,controller){const wrap=el(doc,'div','uw-platform-page');wrap.append(pageHead(doc,'Platforma boshqaruvi','Faqat serverdagi haqiqiy platforma KPI va diqqat talab qiladigan holatlar.'));const p=inlineState(doc,state.dashboardStatus,{loading:'Dashboard yuklanmoqda',error:'Dashboard yuklanmadi',retry:()=>controller.loadDashboard()});if(p){wrap.append(p);return wrap;}const d=state.dashboard||{};const grid=el(doc,'div','uw-platform-stat-grid uw-platform-admin-kpis');grid.append(stat(doc,'Faol do‘konlar',Number(d.activeShopsCount||0)),stat(doc,'Yangi arizalar',Number(d.newRequestsCount||0)),stat(doc,'7 kunda tugaydi',Number(d.expiringSoonCount||0)),stat(doc,'Muzlatilgan',Number(d.expiredCount||0)),stat(doc,'Ochiq support',Number(d.supportOpenCount||0)),stat(doc,'Ownerlar',Number(d.totalUsersCount||0)));wrap.append(grid);const two=el(doc,'div','uw-platform-admin-grid');const attention=el(doc,'section','uw-platform-card');attention.append(el(doc,'h2','',"Diqqat talab qiladi"));const items=list(d.attentionItems);if(!items.length)attention.append(el(doc,'p','uw-muted','Hozircha shoshilinch holat yo‘q.'));else for(const item of items.slice(0,30)){const b=el(doc,'button','uw-platform-admin-row');b.type='button';const target=item.requestId?`/platform/admin/requests/${encodeURIComponent(item.requestId)}`:item.ticketId?`/platform/admin/support/${encodeURIComponent(item.ticketId)}`:item.shopId?`/platform/admin/shops/${encodeURIComponent(item.shopId)}`:'/platform/admin';b.addEventListener('click',()=>onNavigate?.(target));const cp=el(doc,'span','uw-platform-admin-row__copy');cp.append(el(doc,'strong','',item.label||item.type||'Holat'),el(doc,'small','',item.detail||''));b.append(badge(doc,String(item.type||'').replaceAll('_',' '),item.type==='GRACE_EXPIRED'?'danger':'warning'),cp);attention.append(b);}two.append(attention);const recent=el(doc,'section','uw-platform-card');recent.append(el(doc,'h2','',"Yangi do‘konlar"));for(const s of list(d.recentShops).slice(0,10)){const b=el(doc,'button','uw-platform-admin-row');b.type='button';b.addEventListener('click',()=>onNavigate?.(`/platform/admin/shops/${encodeURIComponent(s.id)}`));const cp=el(doc,'span','uw-platform-admin-row__copy');cp.append(el(doc,'strong','',s.public_code||s.id),el(doc,'small','',dateTime(s.created_at||s.createdAt)));b.append(cp,badge(doc,statusLabel(s.status),statusTone(s.status)));recent.append(b);}if(!list(d.recentShops).length)recent.append(el(doc,'p','uw-muted',"Do‘kon yo‘q."));two.append(recent);wrap.append(two);return wrap;}

function shopAccessRow(doc,label,shop,key,controller){const enabled=shop?.[`${key}AccessGranted`]===true;const row=el(doc,'div','uw-platform-admin-access');const copy=el(doc,'div');copy.append(el(doc,'strong','',label),el(doc,'small','uw-muted',enabled?'Platforma ruxsati berilgan':'Platforma ruxsati yopiq'));row.append(copy,createButton({label:enabled?'O‘chirish':'Ruxsat berish',variant:enabled?'ghost':'secondary',size:'sm',busy:stateBusy(controller,`access:${key}`),onClick:()=>controller.setIntegrationAccess(shop.id,key,!enabled)},doc));return row;}
function stateBusy(controller,key){return controller.getState().mutationStatus===key;}
function shopsView(doc,state,onNavigate,controller,params){const wrap=el(doc,'div','uw-platform-page');const selected=params?.shopId?state.shops.find(s=>s.id===String(params.shopId)):null;if(selected){wrap.append(createButton({label:"← Do‘konlar",variant:'ghost',onClick:()=>onNavigate?.('/platform/admin/shops')},doc),pageHead(doc,selected.botName||selected.botUsername||selected.publicCode||"Do‘kon",`${selected.publicCode||selected.id} · ${statusLabel(selected.status)}`));const hero=el(doc,'section','uw-platform-card');const top=el(doc,'div','uw-platform-admin-detail-head');const cp=el(doc,'div');cp.append(el(doc,'small','uw-muted','Shop ID'),el(doc,'h2','',selected.id),el(doc,'p','uw-muted',`Owner: ${selected.ownerTelegramId||'—'} · Tarif: ${selected.tariffName||'Tarifsiz'} · Tugash: ${date(selected.subscriptionExpiresAt)}`));top.append(cp,badge(doc,statusLabel(selected.status),statusTone(selected.status)));hero.append(top);const detail=el(doc,'div','uw-platform-detail-grid');for(const [l,v] of [['Bot',selected.botUsername?`@${selected.botUsername}`:'—'],['Mahsulot limiti',selected.productLimit??'—'],['BILLZ',selected.billzConnectionStatus||'DISCONNECTED'],['Click',selected.clickConnectionStatus||'DISCONNECTED'],['Payme',selected.paymeConnectionStatus||'DISCONNECTED'],['Uzum',selected.uzumConnectionStatus||'DISCONNECTED']]){const x=el(doc,'div');x.append(el(doc,'small','',l),el(doc,'strong','',v));detail.append(x);}hero.append(detail);wrap.append(hero);
    const grid=el(doc,'div','uw-platform-admin-grid');const access=el(doc,'section','uw-platform-card');access.append(el(doc,'h2','',"Integratsiya ruxsatlari"),shopAccessRow(doc,'BILLZ',selected,'billz',controller),shopAccessRow(doc,'Click',selected,'click',controller),shopAccessRow(doc,'Payme',selected,'payme',controller),shopAccessRow(doc,'Uzum',selected,'uzum',controller));grid.append(access);
    const lifecycle=el(doc,'section','uw-platform-card');lifecycle.append(el(doc,'h2','',"Lifecycle amallari"));const grant=el(doc,'form','uw-platform-admin-form-row');const days=nameControl(doc.createElement('input'),'Qo‘shiladigan kunlar');days.type='number';days.min='1';days.max='365';days.placeholder='Kun';const reason=nameControl(doc.createElement('input'),'Kun qo‘shish sababi');reason.placeholder='Sabab';grant.append(days,reason,createButton({label:'Kun qo‘shish',size:'sm',busy:state.mutationStatus==='grant-days'},doc));grant.addEventListener('submit',e=>{e.preventDefault?.();controller.grantDays(selected.id,days.value,reason.value);});lifecycle.append(grant);if(selected.status==='ACTIVE'){const f=el(doc,'form','uw-platform-admin-form-row');const why=nameControl(doc.createElement('input'),'Muzlatish sababi');why.placeholder='Muzlatish sababi';f.append(why,createButton({label:'Muzlatish',variant:'danger',size:'sm',busy:state.mutationStatus==='freeze'},doc));f.addEventListener('submit',e=>{e.preventDefault?.();controller.freezeShop(selected.id,why.value);});lifecycle.append(f);}if(selected.status==='FROZEN'){lifecycle.append(createButton({label:'Qayta faollashtirish',variant:'secondary',busy:state.mutationStatus==='reactivate',onClick:()=>controller.reactivateShop(selected.id)},doc));const ex=el(doc,'form','uw-platform-admin-form-row');const d=nameControl(doc.createElement('input'),'Saqlash muddatini uzaytirish kunlari');d.type='number';d.min='1';d.max='365';d.placeholder='Kun';const why=nameControl(doc.createElement('input'),'Saqlash muddatini uzaytirish sababi');why.placeholder='Sabab (ixtiyoriy)';ex.append(d,why,createButton({label:'Saqlash muddatini uzaytirish',variant:'secondary',size:'sm',busy:state.mutationStatus==='extend-grace'},doc));ex.addEventListener('submit',e=>{e.preventDefault?.();controller.extendFrozenGrace(selected.id,d.value,why.value);});lifecycle.append(ex);}if(selected.status!=='TERMINATED'){const t=el(doc,'form','uw-platform-admin-form-row uw-platform-admin-danger-zone');const why=nameControl(doc.createElement('input'),"Do‘konni butunlay o‘chirish sababi");why.placeholder="Butunlay o‘chirish sababi";const b=createButton({label:"Do‘konni butunlay o‘chirish",variant:'danger',size:'sm',busy:state.mutationStatus==='terminate'},doc);t.append(why,b);t.addEventListener('submit',e=>{e.preventDefault?.();if(globalThis.confirm?.("Bu amal do‘kon ma’lumotlarini purge qiladi. Davom etilsinmi?")===false)return;controller.terminateShop(selected.id,why.value);});lifecycle.append(t);}grid.append(lifecycle);wrap.append(grid);
    const historyGrid=el(doc,'div','uw-platform-admin-grid');const hist=el(doc,'section','uw-platform-card');hist.append(el(doc,'h2','',"Obuna tarixi"));for(const h of state.shopHistory){const r=el(doc,'div','uw-platform-admin-history');r.append(el(doc,'strong','',h.newTariffName||h.eventType||'Obuna'),el(doc,'small','uw-muted',`${dateTime(h.createdAt)} · ${h.purchasedAmount!=null?money(h.purchasedAmount):''}`));hist.append(r);}if(!state.shopHistory.length)hist.append(el(doc,'p','uw-muted','Tarix yozuvi yo‘q.'));const audit=el(doc,'section','uw-platform-card');audit.append(el(doc,'h2','',"Platforma admin auditi"));for(const a of state.shopActions){const r=el(doc,'div','uw-platform-admin-history');r.append(el(doc,'strong','',String(a.action||'ACTION').replaceAll('_',' ')),el(doc,'small','uw-muted',`${dateTime(a.createdAt)} · Admin ${a.adminTgId||'—'}`));audit.append(r);}if(!state.shopActions.length)audit.append(el(doc,'p','uw-muted','Audit yozuvi yo‘q.'));historyGrid.append(hist,audit);wrap.append(historyGrid);return wrap;}
  wrap.append(pageHead(doc,"Barcha do‘konlar",'Platformadagi tenantlar. Oddiy shop-admin bu ro‘yxatni ko‘ra olmaydi.'));const panel=inlineState(doc,state.shopsStatus,{loading:"Do‘konlar yuklanmoqda",error:"Do‘konlar yuklanmadi",retry:()=>controller.loadShops()});if(panel){wrap.append(panel);return wrap;}const filters=el(doc,'div','uw-platform-admin-toolbar');const q=nameControl(doc.createElement('input'),"Do‘konlarni qidirish");q.type='search';q.placeholder="Do‘kon, bot, public code yoki owner ID";q.value=state.shopQuery||'';q.addEventListener('input',e=>controller.setShopQuery(e.target?.value||''));const sel=nameControl(doc.createElement('select'),"Do‘kon holati filtri");for(const v of ['ALL','ACTIVE','FROZEN','PROVISIONING','TERMINATED']){const o=doc.createElement('option');o.value=v;o.textContent=v==='ALL'?'Barcha holatlar':statusLabel(v);o.selected=v===state.shopStatusFilter;sel.append(o);}sel.addEventListener('change',e=>controller.setShopStatusFilter(e.target?.value||'ALL'));filters.append(q,sel);wrap.append(filters);const needle=String(state.shopQuery||'').trim().toLowerCase();const rows=state.shops.filter(s=>(state.shopStatusFilter==='ALL'||s.status===state.shopStatusFilter)&&(!needle||[s.publicCode,s.botUsername,s.botName,s.ownerTelegramId,s.tariffName].some(v=>String(v||'').toLowerCase().includes(needle))));const table=el(doc,'div','uw-platform-admin-table');const head=el(doc,'div','uw-platform-admin-table__row is-head');for(const h of ['Do‘kon','Holat','Tarif','Owner','Obuna'])head.append(el(doc,'span','',h));table.append(head);for(const s of rows){const r=el(doc,'button','uw-platform-admin-table__row');r.type='button';r.addEventListener('click',()=>onNavigate?.(`/platform/admin/shops/${encodeURIComponent(s.id)}`));r.append(el(doc,'span','',s.botName||s.botUsername||s.publicCode||s.id),badge(doc,statusLabel(s.status),statusTone(s.status)),el(doc,'span','',s.tariffName||'Tarifsiz'),el(doc,'span','',s.ownerTelegramId||'—'),el(doc,'span','',date(s.subscriptionExpiresAt)));table.append(r);}if(!rows.length)wrap.append(createStatePanel({kind:'empty',title:'Natija topilmadi',message:'Qidiruv yoki filtrni o‘zgartiring.'},doc));else wrap.append(table);return wrap;}

function requestSummary(doc,r){const box=el(doc,'div','uw-platform-detail-grid');for(const [l,v] of [["So‘rov",r.kind==='NEW_SHOP'?"Yangi do‘kon":r.upgradeAction==='EXTEND'?'Uzaytirish':'Tarif almashtirish'],['Tarif',r.tariffName||'—'],['Summa',money(r.tariffPrice)],['To‘lov',r.paymentMethod||'—'],['Foydalanuvchi',r.requesterUsername?`@${r.requesterUsername}`:(r.requesterFirstName||r.requesterTelegramId||'—')],['Sana',dateTime(r.createdAt)]]){const x=el(doc,'div');x.append(el(doc,'small','',l),el(doc,'strong','',v));box.append(x);}return box;}
function requestsView(doc,state,onNavigate,controller,params){const wrap=el(doc,'div','uw-platform-page');const id=params?.requestId?String(params.requestId):null;const r=id?(state.requestDetail||state.requests.find(x=>x.id===id)):null;if(r){wrap.append(createButton({label:'← Arizalar',variant:'ghost',onClick:()=>onNavigate?.('/platform/admin/requests')},doc),pageHead(doc,`Ariza #${r.id}`,`${statusLabel(r.status)} · ${r.tariffName||'Tarif'}`));const card=el(doc,'section','uw-platform-card');card.append(requestSummary(doc,r));const actions=el(doc,'div','uw-platform-inline-actions');if(r.hasReceipt)actions.append(createButton({label:'Chekni ochish',variant:'secondary',onClick:async()=>{const x=await controller.getReceiptUrl(r.id);if(x.ok)openExternal(x.data?.url);}},doc));if(r.hasBotPhoto)actions.append(createButton({label:'Bot rasmini ochish',variant:'ghost',onClick:async()=>{const x=await controller.getBotPhotoUrl(r.id);if(x.ok)openExternal(x.data?.url);}},doc));if(r.status==='NEW'&&r.paymentClaimedAt){actions.append(createButton({label:'Tasdiqlash',busy:state.mutationStatus==='approve-request',onClick:()=>controller.approveRequest(r.id)},doc));const reject=el(doc,'form','uw-platform-admin-form-row');const reason=nameControl(doc.createElement('input'),'Arizani rad etish sababi');reason.placeholder='Rad etish sababi';reject.append(reason,createButton({label:'Rad etish',variant:'danger',size:'sm',busy:state.mutationStatus==='reject-request'},doc));reject.addEventListener('submit',e=>{e.preventDefault?.();controller.rejectRequest(r.id,reason.value);});card.append(reject);}if(r.awaitingProvisioning){const provision=el(doc,'form','uw-platform-admin-secret-form');const token=nameControl(doc.createElement('input'),'Bot token');token.type='password';token.autocomplete='off';token.placeholder='Bot token — faqat bir martalik yuboriladi';const b=createButton({label:"Do‘konni yaratish",busy:state.mutationStatus==='provision'},doc);provision.append(el(doc,'p','uw-muted',`${r.requestedShopName||"Yangi do‘kon"}${r.requestedBotName?` · Bot nomi: ${r.requestedBotName}`:''}`),token,b);provision.addEventListener('submit',async(e)=>{e.preventDefault?.();try{await controller.provisionShop(r.id,token.value);}finally{token.value='';}});card.append(provision);}if(actions.children?.length)card.append(actions);wrap.append(card);const timeline=el(doc,'section','uw-platform-card');timeline.append(el(doc,'h2','',"Ariza tarixi"));for(const h of state.requestHistory){const row=el(doc,'div','uw-platform-admin-history');row.append(el(doc,'strong','',String(h.eventType||'EVENT').replaceAll('_',' ')),el(doc,'small','uw-muted',`${dateTime(h.createdAt)} · ${h.actorType||'SYSTEM'}${h.actorTelegramId?` · ${h.actorTelegramId}`:''}`));timeline.append(row);}if(!state.requestHistory.length)timeline.append(el(doc,'p','uw-muted','Tarix yozuvi yo‘q.'));wrap.append(timeline);return wrap;}
  wrap.append(pageHead(doc,'Obuna va do‘kon arizalari','Tasdiqlash/rad etish server qoidalari bilan bajariladi.'));const controls=el(doc,'div','uw-platform-admin-toolbar');const sel=nameControl(doc.createElement('select'),'Ariza holati filtri');for(const v of ['ALL','NEW','APPROVED','REJECTED']){const o=doc.createElement('option');o.value=v;o.textContent=v==='ALL'?'Barcha arizalar':statusLabel(v);o.selected=v===state.requestStatusFilter;sel.append(o);}sel.addEventListener('change',()=>controller.loadRequests({status:sel.value}));controls.append(sel);wrap.append(controls);const p=inlineState(doc,state.requestsStatus,{loading:'Arizalar yuklanmoqda',error:'Arizalar yuklanmadi',retry:()=>controller.loadRequests()});if(p){wrap.append(p);return wrap;}const table=el(doc,'div','uw-platform-admin-table');const head=el(doc,'div','uw-platform-admin-table__row is-head');for(const h of ['Ariza','Foydalanuvchi','Tarif','Summa','Holat'])head.append(el(doc,'span','',h));table.append(head);for(const x of state.requests){const row=el(doc,'button','uw-platform-admin-table__row');row.type='button';row.addEventListener('click',()=>onNavigate?.(`/platform/admin/requests/${encodeURIComponent(x.id)}`));row.append(el(doc,'span','',x.kind==='NEW_SHOP'?(x.requestedShopName||"Yangi do‘kon"):(x.upgradeAction==='EXTEND'?'Uzaytirish':'Tarif almashtirish')),el(doc,'span','',x.requesterUsername?`@${x.requesterUsername}`:(x.requesterFirstName||x.requesterTelegramId||'—')),el(doc,'span','',x.tariffName||'—'),el(doc,'span','',money(x.tariffPrice)),badge(doc,statusLabel(x.status),statusTone(x.status)));table.append(row);}if(!state.requests.length)wrap.append(createStatePanel({kind:'empty',title:'Ariza yo‘q',message:'Tanlangan holatda ariza topilmadi.'},doc));else wrap.append(table);return wrap;}

function supportView(doc,state,onNavigate,controller,params){const wrap=el(doc,'div','uw-platform-page');const id=params?.ticketId?Number(params.ticketId):null;const ticket=id?state.tickets.find(t=>Number(t.id)===id):null;if(ticket){wrap.append(createButton({label:'← Support',variant:'ghost',onClick:()=>onNavigate?.('/platform/admin/support')},doc),pageHead(doc,`Murojaat #${ticket.id}`,`${ticket.type==='BUG_REPORT'?'Bug report':'Support'} · ${statusLabel(ticket.status)}`));const meta=el(doc,'section','uw-platform-card');meta.append(el(doc,'p','uw-muted',`${ticket.requesterUsername?`@${ticket.requesterUsername}`:(ticket.requesterFirstName||'Foydalanuvchi')} · ${dateTime(ticket.createdAt)}`));wrap.append(meta);const thread=el(doc,'section','uw-platform-card uw-platform-thread');for(const m of state.messages){const msg=el(doc,'div',`uw-platform-message ${m.sender==='ADMIN'?'is-admin':'is-user'}`);msg.append(el(doc,'small','',m.sender==='ADMIN'?'Super Admin':'Foydalanuvchi'),el(doc,'p','',m.body||''),el(doc,'time','',dateTime(m.createdAt)));if(m.attachmentUrl){const a=el(doc,'a','',"Biriktirma ↗");a.href=safeUrl(m.attachmentUrl)||'#';a.target='_blank';a.rel='noopener';msg.append(a);}thread.append(msg);}if(ticket.status!=='CLOSED'){const form=el(doc,'form','uw-platform-reply');const ta=doc.createElement('textarea');ta.placeholder='Javob yozing…';form.append(ta,createButton({label:'Javob yuborish',busy:state.mutationStatus==='support-send'},doc));form.addEventListener('submit',async(e)=>{e.preventDefault?.();const body=ta.value.trim();if(!body)return;const r=await controller.sendSupportMessage(ticket.id,body);if(r.ok)ta.value='';});thread.append(form,createButton({label:'Murojaatni yopish',variant:'ghost',busy:state.mutationStatus==='support-close',onClick:()=>controller.closeSupportTicket(ticket.id)},doc));}wrap.append(thread);return wrap;}
  wrap.append(pageHead(doc,'Platforma support','Barcha foydalanuvchi support va bug-report murojaatlari.'));const controls=el(doc,'div','uw-platform-admin-toolbar');const sel=nameControl(doc.createElement('select'),'Support holati filtri');for(const v of ['ALL','OPEN','ANSWERED','CLOSED']){const o=doc.createElement('option');o.value=v;o.textContent=v==='ALL'?'Barcha holatlar':statusLabel(v);o.selected=v===state.supportStatusFilter;sel.append(o);}sel.addEventListener('change',()=>controller.loadSupport({status:sel.value}));controls.append(sel);wrap.append(controls);const p=inlineState(doc,state.supportStatus,{loading:'Support yuklanmoqda',error:'Support yuklanmadi',retry:()=>controller.loadSupport()});if(p){wrap.append(p);return wrap;}const listBox=el(doc,'section','uw-platform-card');for(const t of state.tickets){const row=el(doc,'button','uw-platform-admin-row');row.type='button';row.addEventListener('click',()=>onNavigate?.(`/platform/admin/support/${encodeURIComponent(t.id)}`));const cp=el(doc,'span','uw-platform-admin-row__copy');cp.append(el(doc,'strong','',t.subject||`${t.type==='BUG_REPORT'?'Bug':'Support'} #${t.id}`),el(doc,'small','',`${t.requesterUsername?`@${t.requesterUsername}`:(t.requesterFirstName||'Foydalanuvchi')} · ${dateTime(t.createdAt)}`));row.append(cp,badge(doc,statusLabel(t.status),statusTone(t.status)));listBox.append(row);}if(!state.tickets.length)listBox.append(el(doc,'p','uw-muted','Murojaat yo‘q.'));wrap.append(listBox);return wrap;}

function tariffForm(doc,controller,row=null){const form=el(doc,'form','uw-platform-admin-tariff-form');const name=nameControl(doc.createElement('input'),'Tarif nomi');name.placeholder='Tarif nomi';name.value=row?.name||'';const price=nameControl(doc.createElement('input'),'Tarif narxi');price.type='number';price.min='0';price.placeholder='Narx';price.value=row?.price??'';const limit=nameControl(doc.createElement('input'),'Mahsulot limiti');limit.type='number';limit.min='1';limit.placeholder='Mahsulot limiti';limit.value=row?.productLimit??'';const sort=nameControl(doc.createElement('input'),'Tarif tartibi');sort.type='number';sort.placeholder='Tartib';sort.value=row?.sortOrder??0;const features=nameControl(doc.createElement('textarea'),'Tarif xususiyatlari');features.placeholder='Xususiyatlar — har qatorga bittadan';features.value=list(row?.features).join('\n');const active=doc.createElement('input');active.type='checkbox';active.checked=row?.isActive!==false;const popular=doc.createElement('input');popular.type='checkbox';popular.checked=row?.isPopular===true;const aLabel=el(doc,'label','uw-platform-admin-check');aLabel.append(active,el(doc,'span','','Faol'));const pLabel=el(doc,'label','uw-platform-admin-check');pLabel.append(popular,el(doc,'span','','Ommabop'));form.append(name,price,limit,sort,features,aLabel,pLabel,createButton({label:row?'Saqlash':'Tarif qo‘shish'},doc));form.addEventListener('submit',e=>{e.preventDefault?.();controller.saveTariff({id:row?.id,name:name.value,price:price.value,productLimit:limit.value,sortOrder:sort.value,isActive:active.checked,isPopular:popular.checked,features:String(features.value||'').split('\n')});});return form;}
function tariffsView(doc,state,controller){const wrap=el(doc,'div','uw-platform-page');wrap.append(pageHead(doc,'Tariflar','Tarif narxi, limit va xususiyatlari server bazasida boshqariladi.'));const p=inlineState(doc,state.tariffsStatus,{loading:'Tariflar yuklanmoqda',error:'Tariflar yuklanmadi',retry:()=>controller.loadTariffs()});if(p){wrap.append(p);return wrap;}const create=el(doc,'section','uw-platform-card');create.append(el(doc,'h2','',"Yangi tarif"),tariffForm(doc,controller));wrap.append(create);for(const t of state.tariffs){const card=el(doc,'section','uw-platform-card');const head=el(doc,'div','uw-platform-admin-detail-head');const cp=el(doc,'div');cp.append(el(doc,'h2','',t.name),el(doc,'p','uw-muted',`${money(t.price)} · ${t.productLimit==null?'Limitsiz':`${t.productLimit} mahsulot`}`));head.append(cp,badge(doc,t.isActive?'Faol':'O‘chiq',t.isActive?'success':'neutral'));card.append(head,tariffForm(doc,controller,t));wrap.append(card);}return wrap;}

function analyticsView(doc,state,controller){const wrap=el(doc,'div','uw-platform-page');wrap.append(pageHead(doc,'Platforma analitikasi','Tasdiqlangan subscription requestlaridan server hisoblagan real ko‘rsatkichlar.'));const controls=el(doc,'div','uw-platform-admin-toolbar');const sel=nameControl(doc.createElement('select'),'Analitika davri');for(const v of ['7d','30d','90d','all']){const o=doc.createElement('option');o.value=v;o.textContent=v==='all'?'Barcha davr':v;o.selected=v===state.analyticsPeriod;sel.append(o);}sel.addEventListener('change',()=>controller.loadAnalytics(sel.value));controls.append(sel);wrap.append(controls);const p=inlineState(doc,state.analyticsStatus,{loading:'Analitika yuklanmoqda',error:'Analitika yuklanmadi',retry:()=>controller.loadAnalytics()});if(p){wrap.append(p);return wrap;}const a=state.analytics||{};const grid=el(doc,'div','uw-platform-stat-grid uw-platform-admin-kpis');grid.append(stat(doc,'Tasdiqlangan',Number(a.totalCount||0)),stat(doc,"Yangi do‘kon",Number(a.newShopCount||0)),stat(doc,'Uzaytirish',Number(a.renewalCount||0)),stat(doc,'Tarif almashtirish',Number(a.planChangeCount||0)),stat(doc,'Tushum',money(a.revenue||0)),stat(doc,'30 kun retention',a.retentionRate==null?'—':`${a.retentionRate}%`,`${Number(a.retentionCohortSize||0)} shop cohort`));wrap.append(grid);const g=el(doc,'div','uw-platform-admin-grid');const tariffs=el(doc,'section','uw-platform-card');tariffs.append(el(doc,'h2','',"Tarif kesimi"));for(const r of list(a.byTariff)){const row=el(doc,'div','uw-platform-admin-history');row.append(el(doc,'strong','',r.tariffName||'Noma’lum'),el(doc,'small','uw-muted',`${Number(r.count||0)} ta · ${money(r.revenue||0)}`));tariffs.append(row);}const period=el(doc,'section','uw-platform-card');period.append(el(doc,'h2','',"To‘lov davri"));for(const key of ['MONTHLY','ANNUAL']){const r=a.byPeriod?.[key]||{};const row=el(doc,'div','uw-platform-admin-history');row.append(el(doc,'strong','',key==='ANNUAL'?'Yillik':'Oylik'),el(doc,'small','uw-muted',`${Number(r.count||0)} ta · ${money(r.revenue||0)}`));period.append(row);}g.append(tariffs,period);wrap.append(g);const timeline=el(doc,'section','uw-platform-card');timeline.append(el(doc,'h2','',"Savdo dinamikasi"));const table=el(doc,'div','uw-platform-admin-analytics-table');for(const r of list(a.salesTimeline)){const row=el(doc,'div');row.append(el(doc,'span','',r.day||r.label||'—'),el(doc,'span','',`${Number(r.count||0)} ta`),el(doc,'strong','',money(r.revenue||0)));table.append(row);}if(!list(a.salesTimeline).length)table.append(el(doc,'p','uw-muted','Tanlangan davrda tasdiqlangan to‘lov yo‘q.'));timeline.append(table);wrap.append(timeline);return wrap;}

function lifecycleForm(doc,state,controller){const s=state.lifecycleSettings||{};const form=el(doc,'form','uw-platform-admin-settings-form');const retention=nameControl(doc.createElement('input'),'Ma’lumot saqlash muddati (kun)');retention.type='number';retention.min='1';retention.max='365';retention.value=s.retentionDays??30;const label=nameControl(doc.createElement('input'),'Support tugmasi nomi');label.value=s.supportLabel||'';label.placeholder='Support tugmasi matni';const url=nameControl(doc.createElement('input'),'Support URL');url.value=s.supportUrl||'';url.placeholder='Support URL';const auto=doc.createElement('input');auto.type='checkbox';auto.checked=s.autoFreezeOnExpiry!==false;const autoLabel=el(doc,'label','uw-platform-admin-check');autoLabel.append(auto,el(doc,'span','','Muddat tugaganda avtomatik muzlatish'));form.append(el(doc,'label','uw-field-label','Ma’lumot saqlash muddati (kun)'),retention,el(doc,'label','uw-field-label','Support nomi'),label,el(doc,'label','uw-field-label','Support URL'),url,autoLabel,createButton({label:'Lifecycle’ni saqlash'},doc));form.addEventListener('submit',e=>{e.preventDefault?.();controller.saveLifecycleSettings({...s,retentionDays:Number(retention.value),supportLabel:label.value,supportUrl:url.value,autoFreezeOnExpiry:auto.checked});});return form;}
function paymentCardForm(doc,state,controller){const s=state.paymentInfo||{};const form=el(doc,'form','uw-platform-admin-settings-form');const number=nameControl(doc.createElement('input'),'Karta raqami');number.value=s.cardNumber||'';number.placeholder='Karta raqami';const holder=nameControl(doc.createElement('input'),'Karta egasi');holder.value=s.cardHolder||'';holder.placeholder='Karta egasi';const active=doc.createElement('input');active.type='checkbox';active.checked=s.isActive!==false;const lab=el(doc,'label','uw-platform-admin-check');lab.append(active,el(doc,'span','','Faol'));form.append(number,holder,lab,createButton({label:'Kartani saqlash'},doc));form.addEventListener('submit',e=>{e.preventDefault?.();controller.savePaymentInfo({cardNumber:number.value,cardHolder:holder.value,isActive:active.checked});});return form;}
function paymentMethodForm(doc,row,controller){const form=el(doc,'form','uw-platform-admin-method-form');const type=nameControl(doc.createElement('select'),'To‘lov usuli turi');for(const v of ['CLICK','PAYME','PAYNET']){const o=doc.createElement('option');o.value=v;o.textContent=v;o.selected=v===String(row?.methodType||'CLICK').toUpperCase();type.append(o);}const name=nameControl(doc.createElement('input'),'To‘lov usuli nomi');name.value=row?.displayName||'';name.placeholder='Ko‘rinadigan nom';const url=nameControl(doc.createElement('input'),'To‘lov URL');url.value=row?.paymentUrl||'';url.placeholder='https://...';const sort=nameControl(doc.createElement('input'),'To‘lov usuli tartibi');sort.type='number';sort.value=row?.sortOrder??0;const active=doc.createElement('input');active.type='checkbox';active.checked=row?.isActive!==false;const lab=el(doc,'label','uw-platform-admin-check');lab.append(active,el(doc,'span','','Faol'));form.append(type,name,url,sort,lab,createButton({label:row?'Saqlash':'Usul qo‘shish',size:'sm'},doc));form.addEventListener('submit',e=>{e.preventDefault?.();controller.savePaymentMethod({id:row?.id,methodType:type.value,displayName:name.value,paymentUrl:url.value,sortOrder:sort.value,isActive:active.checked});});return form;}
function notificationForm(doc,row,controller){const form=el(doc,'form','uw-platform-admin-notification-form');const body=nameControl(doc.createElement('textarea'),'Avtomatik xabar matni');body.value=row?.body||'';body.placeholder='Xabar matni';const image=nameControl(doc.createElement('input'),'Avtomatik xabar rasmi URL');image.value=row?.imageUrl||'';image.placeholder='https://... rasm URL (ixtiyoriy)';const active=doc.createElement('input');active.type='checkbox';active.checked=row?.isActive!==false;const lab=el(doc,'label','uw-platform-admin-check');lab.append(active,el(doc,'span','','Faol'));const actions=el(doc,'div','uw-platform-inline-actions');actions.append(createButton({label:'Saqlash',size:'sm'},doc),createButton({label:'Sinov yuborish',variant:'secondary',size:'sm',type:'button',onClick:()=>controller.sendTestNotification(row.type)},doc));form.append(el(doc,'strong','',row.type||'TEMPLATE'),body,image,lab,actions);form.addEventListener('submit',e=>{e.preventDefault?.();controller.saveNotificationTemplate({type:row.type,body:body.value,imageUrl:image.value,isActive:active.checked});});return form;}
function settingsView(doc,state,controller){const wrap=el(doc,'div','uw-platform-page');wrap.append(pageHead(doc,'Platforma sozlamalari','Lifecycle, obuna to‘lovi va avtomatik xabarlar. Secret credentiallar bu sahifada saqlanmaydi.',createButton({label:'Platform botni sozlash',variant:'secondary',onClick:()=>{if(globalThis.confirm?.('Platform bot webhook/menu konfiguratsiyasi yangilansinmi?')===false)return;controller.setupPlatformBot();}},doc)));const p=inlineState(doc,state.settingsStatus,{loading:'Sozlamalar yuklanmoqda',error:'Sozlamalar yuklanmadi',retry:()=>controller.loadSettings()});if(p){wrap.append(p);return wrap;}const grid=el(doc,'div','uw-platform-admin-grid');const life=el(doc,'section','uw-platform-card');life.append(el(doc,'h2','',"Do‘kon lifecycle"),lifecycleForm(doc,state,controller));const card=el(doc,'section','uw-platform-card');card.append(el(doc,'h2','',"Karta orqali to‘lov"),paymentCardForm(doc,state,controller));grid.append(life,card);wrap.append(grid);const methods=el(doc,'section','uw-platform-card');methods.append(el(doc,'h2','',"Tashqi to‘lov havolalari"),paymentMethodForm(doc,null,controller));for(const m of state.paymentMethods)methods.append(paymentMethodForm(doc,m,controller));wrap.append(methods);const notifications=el(doc,'section','uw-platform-card');notifications.append(el(doc,'h2','',"Telegram avtomatik xabarlari"));for(const t of state.notificationTemplates)notifications.append(notificationForm(doc,t,controller));if(!state.notificationTemplates.length)notifications.append(el(doc,'p','uw-muted','Xabar shablonlari topilmadi.'));wrap.append(notifications);return wrap;}

export function createPlatformAdminView({controller,state=controller?.getState?.()||{},section='overview',params={},onNavigate,onSignedOut}={},documentRef){const doc=getDocument(documentRef);if(!controller)throw new TypeError('controller kerak');const root=el(doc,'div','uw-platform-admin uw-root');root.dataset.feature='platform-admin';root.append(adminHeader(doc,state,{onNavigate,onLogout:async()=>{const r=await controller.signOut();if(r.ok)onSignedOut?.();}}));if(state.status==='loading'||state.status==='idle'){root.append(createStatePanel({kind:'loading',title:'Super Admin tekshirilmoqda',message:'Markaziy platforma vakolati serverda tekshirilmoqda.'},doc));return {element:root};}if(state.status==='error'){root.append(createStatePanel({kind:'error',title:'Platforma yuklanmadi',message:state.error?.message||'Server bilan ulanishda xato.',actionLabel:'Qayta urinish',onAction:()=>controller.load()},doc));return {element:root};}if(state.status==='forbidden'||state.isSuperAdmin!==true){root.append(createStatePanel({kind:'permission',title:'Super Admin vakolati kerak',message:'Do‘kon OWNER/MANAGER/STAFF roli markaziy platforma Super Admin huquqini bermaydi.',actionLabel:'Platforma portaliga qaytish',onAction:()=>onNavigate?.('/platform/app')},doc));return {element:root};}
  const body=el(doc,'div','uw-platform-admin__body');body.append(adminNav(doc,section,onNavigate));const main=el(doc,'main','uw-platform-admin__main');main.id='uw-main-content';if(state.notice)main.append(createStatePanel({kind:state.notice.kind==='error'?'error':state.notice.kind==='warning'?'warning':'success',title:state.notice.kind==='error'?'Amal bajarilmadi':state.notice.kind==='warning'?'Eslatma':'Bajarildi',message:state.notice.message},doc));if(section==='shops')main.append(shopsView(doc,state,onNavigate,controller,params));else if(section==='requests')main.append(requestsView(doc,state,onNavigate,controller,params));else if(section==='support')main.append(supportView(doc,state,onNavigate,controller,params));else if(section==='tariffs')main.append(tariffsView(doc,state,controller));else if(section==='analytics')main.append(analyticsView(doc,state,controller));else if(section==='settings')main.append(settingsView(doc,state,controller));else main.append(dashboardView(doc,state,onNavigate,controller));body.append(main);root.append(body);return {element:root};}
