import { createButton, createCard, createSelectField, createStatePanel, createTextField } from '../../components/ui.js';
import { fail, ok } from '../../services/ports/result.js';

function clone(value){ return value == null ? value : structuredClone(value); }
function text(value){ return String(value ?? '').trim(); }
function hasPermission(actor, permission){ const list=Array.isArray(actor?.permissions)?actor.permissions:[]; return list.includes('*')||list.includes(permission); }
function throwResult(result){ if(result?.ok) return result.data; const error=new Error(result?.error?.message||'Admin action bajarilmadi'); error.code=result?.error?.code; error.details=result?.error; throw error; }

export function createExcelImportController({ adminPort, actor, excelEngine, getCategories=()=>[], getProducts=()=>[], onCatalogMutation, reloadCatalog }={}){
  if(!adminPort?.invoke) throw new TypeError('adminPort kerak');
  if(!excelEngine?.configure || !excelEngine?.handleFile || !excelEngine?.doImport) throw new TypeError('UstoreExcel engine kerak');
  const allowed=hasPermission(actor,'products.import_export');
  let state={status:'idle', error:null, engine:{}, allowed}; const listeners=new Set();
  const snapshot=()=>clone(state); const emit=()=>listeners.forEach(fn=>fn(snapshot()));
  const update=(patch)=>{state={...state,...patch};emit();};
  const sync=(engineState)=>update({engine:clone({busy:engineState.busy,busyText:engineState.busyText,fileName:engineState.fileName,rows:engineState.rows,issues:engineState.issues,rowIssues:engineState.rowIssues,progressDone:engineState.progressDone,progressTotal:engineState.progressTotal,templateStatus:engineState.templateStatus,result:engineState.result,stagedImport:engineState.stagedImport,lastBatch:engineState.lastBatch}),status:'ready'});
  const deny=()=>fail('FORBIDDEN','Excel import uchun products.import_export ruxsati kerak.');
  async function api(action,payload){ return throwResult(await adminPort.invoke(action,payload)); }
  async function load(){ if(!allowed){update({status:'permission',error:deny().error});return deny();} excelEngine.configure({api,getCategories,getProducts,onChange:sync,onCatalogMutation,reloadCatalog,onImportComplete:()=>reloadCatalog?.()}); update({status:'loading',error:null}); try{await excelEngine.prepare?.();sync(excelEngine.getSnapshot?.()||excelEngine.state||{});return ok(snapshot());}catch(e){const r=fail('NETWORK_ERROR',e.message||'Excel modulini tayyorlab bo‘lmadi.',{retryable:true});update({status:'error',error:r.error});return r;} }
  async function chooseFile(file){ if(!allowed)return deny(); if(!file)return fail('VALIDATION_ERROR','Excel faylni tanlang.'); await excelEngine.handleFile({target:{files:[file]}}); return ok(snapshot()); }
  async function process(){ if(!allowed)return deny(); await excelEngine.doImport(); return ok(snapshot()); }
  async function downloadTemplate(){ if(!allowed)return deny(); await excelEngine.downloadTemplate(); return ok(true); }
  function acceptSuggestion(index){ excelEngine.acceptSuggestionAt(Number(index)); return snapshot(); }
  function approveNew(index){ excelEngine.approveNewAt(Number(index)); return snapshot(); }
  async function rollback({confirmed=false}={}){ if(!confirmed)return fail('VALIDATION_ERROR','Rollback alohida tasdiqlanishi kerak.'); await excelEngine.rollbackBatch({confirmed:true}); return ok(snapshot()); }
  async function reset(){ await excelEngine.reset(); return ok(snapshot()); }
  return Object.freeze({getState:snapshot,subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);},load,chooseFile,process,downloadTemplate,acceptSuggestion,approveNew,rollback,reset});
}

function normalizeBillzItem(raw={}){ return {billzProductId:String(raw.billzProductId||''),name:text(raw.name)||'Nomsiz',description:raw.description||null,price:Math.max(0,Number(raw.price)||0),stock:Math.max(0,Number(raw.stock)||0),isVariative:raw.isVariative===true,variants:Array.isArray(raw.variants)?clone(raw.variants):[]}; }
export function createBillzImportController({adminPort,actor,shopCategories=[]}={}){
  if(!adminPort?.invoke) throw new TypeError('adminPort kerak');
  const allowed=hasPermission(actor,'integrations.manage'); let selected=new Set(); let importedSelected=new Set();
  let state={status:'idle',error:null,allowed,connection:null,config:null,billzCategories:[],items:[],count:0,page:1,pageSize:10,search:'',billzCategoryId:'',selectedIds:[],shopCategories:clone(shopCategories),targetCategoryId:null,oldPricePercent:'',imported:[],deleted:[],busy:null,truncated:false}; const listeners=new Set();
  const snap=()=>clone(state); const emit=()=>listeners.forEach(fn=>fn(snap())); const set=(p)=>{state={...state,...p,selectedIds:[...selected],importedSelectedIds:[...importedSelected]};emit();}; const deny=()=>fail('FORBIDDEN','BILLZ uchun integrations.manage ruxsati kerak.');
  async function invoke(action,payload={}){ if(!allowed)return deny(); const r=await adminPort.invoke(action,payload); if(!r.ok)set({error:r.error}); return r; }
  async function load(){ if(!allowed){set({status:'permission',error:deny().error});return deny();} set({status:'loading',error:null}); const status=await invoke('billz_get_status'); if(!status.ok){set({status:'error'});return status;} set({connection:status.data,status:'ready'}); if(status.data?.status==='CONNECTED'){const [cfg,cats]=await Promise.all([invoke('billz_list_config_options'),invoke('billz_get_categories')]); if(cfg.ok)set({config:cfg.data}); if(cats.ok)set({billzCategories:cats.data?.categories||[]}); await browse(1); await loadImported();} return ok(snap()); }
  async function connect(secretToken){ const token=text(secretToken); if(!token)return fail('VALIDATION_ERROR','BILLZ integratsiya kalitini kiriting.'); set({busy:'connect',error:null}); const r=await invoke('billz_connect',{secretToken:token}); set({busy:null}); if(r.ok)await load(); return r; }
  async function disconnect({confirmed=false}={}){ if(!confirmed)return fail('VALIDATION_ERROR','BILLZ ulanishini uzish tasdiqlanishi kerak.'); set({busy:'disconnect'}); const r=await invoke('billz_disconnect',{}); selected.clear(); importedSelected.clear(); set({busy:null,items:[],imported:[],deleted:[]}); if(r.ok)await load(); return r; }
  function setSearch(v){set({search:String(v??''),page:1});return snap();} function setBillzCategory(v){selected.clear();set({billzCategoryId:text(v),page:1});return snap();} function setPageSize(v){const value=String(v)==='ALL'?'ALL':([10,25,50,100].includes(Number(v))?Number(v):10);selected.clear();set({pageSize:value,page:1});return snap();}
  async function browse(page=1){set({busy:'browse',error:null}); const r=await invoke('billz_browse_products',{billzCategoryId:state.billzCategoryId||undefined,search:text(state.search)||undefined,page:Math.max(1,Number(page)||1),limit:state.pageSize}); set({busy:null}); if(!r.ok)return r; const items=(r.data?.items||[]).map(normalizeBillzItem); const visible=new Set(items.map(x=>x.billzProductId)); selected=new Set([...selected].filter(id=>visible.has(id))); set({items,count:Number(r.data?.count)||0,page:Number(r.data?.page)||1,truncated:r.data?.truncated===true}); return ok(snap()); }
  function toggleSelected(id){id=String(id); if(selected.has(id))selected.delete(id);else selected.add(id);set({});return snap();}
  function setTargetCategory(id){set({targetCategoryId:text(id)||null});return snap();} function setOldPricePercent(v){set({oldPricePercent:text(v)});return snap();}
  async function importSelected(){const items=state.items.filter(x=>selected.has(x.billzProductId));if(!items.length)return fail('VALIDATION_ERROR','Import uchun mahsulot tanlang.'); set({busy:'import',error:null}); const payloadItems=items.map(it=>({billzProductId:it.billzProductId,name:it.name,description:it.description,price:it.price,stock:it.stock,variants:it.isVariative?it.variants.map(v=>({billzProductId:v.billzProductId,size:v.size,color:v.color,stock:v.stock})):undefined})); const r=await invoke('billz_import_products',{items:payloadItems,categoryId:state.targetCategoryId,oldPricePercent:state.oldPricePercent}); set({busy:null}); if(r.ok){selected.clear();await browse(state.page);await loadImported();} return r;}
  async function loadImported(){const r=await invoke('billz_list_imported_products',{}); if(r.ok){const rows=r.data?.items||[];const ids=new Set(rows.map(x=>String(x.id)));importedSelected=new Set([...importedSelected].filter(id=>ids.has(id)));set({imported:rows});}return r;}
  function toggleImported(id){id=String(id);if(importedSelected.has(id))importedSelected.delete(id);else importedSelected.add(id);set({});return snap();}
  async function unlinkSelected({confirmed=false}={}){if(!confirmed)return fail('VALIDATION_ERROR','BILLZ bog‘lanishini uzish tasdiqlanishi kerak.');if(!importedSelected.size)return fail('VALIDATION_ERROR','Kamida bitta mahsulot tanlang.');set({busy:'unlink'});const r=await invoke('billz_unlink_products',{productIds:[...importedSelected]});set({busy:null});if(r.ok){importedSelected.clear();await loadImported();}return r;}
  async function loadDeleted(){const r=await invoke('billz_list_deleted_products',{});if(r.ok)set({deleted:r.data?.items||[]});return r;}
  async function restore(productId){const r=await invoke('billz_restore_product',{productId:String(productId)});if(r.ok)await loadDeleted();return r;}
  return Object.freeze({getState:snap,subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);},load,connect,disconnect,setSearch,setBillzCategory,setPageSize,browse,toggleSelected,setTargetCategory,setOldPricePercent,importSelected,loadImported,toggleImported,unlinkSelected,loadDeleted,restore});
}

function txt(doc,tag,cls,value){const n=doc.createElement(tag);if(cls)n.className=cls;n.textContent=String(value??'');return n;}
function money(v){return `${Math.round(Number(v)||0).toLocaleString('uz-UZ')} so‘m`;}
export function createAdminImportsView({excelController,billzController,documentRef=globalThis.document,confirmAction}={}){
  const doc=documentRef;if(!doc?.createElement)throw new Error('DOM document kerak'); const root=doc.createElement('section');root.className='uw-admin-imports';root.dataset.feature='admin-imports';
  const header=doc.createElement('header');header.className='uw-admin-imports__header';header.append(txt(doc,'div','', 'Import va BILLZ'),txt(doc,'small','', 'Mavjud Excel import engine va server actionlari qayta ishlatiladi.'));root.append(header);
  const excel=excelController?.getState?.()||{}; const e=excel.engine||{};
  if(excel.allowed===false) root.append(createStatePanel({kind:'permission',title:'Excel import uchun ruxsat yo‘q'},doc)); else {
    const body=doc.createElement('div');body.className='uw-import-panel'; const actions=doc.createElement('div');actions.className='uw-import-actions';
    const input=doc.createElement('input');input.type='file';input.accept='.xlsx';input.setAttribute('aria-label','Excel fayl tanlash');input.addEventListener('change',()=>{const f=input.files?.[0];if(f)excelController.chooseFile(f);});
    actions.append(input,createButton({label:'Yangi shablon',variant:'secondary',onClick:()=>excelController.downloadTemplate()},doc)); body.append(actions);
    if(e.fileName){body.append(txt(doc,'strong','',e.fileName));const stats=doc.createElement('div');stats.className='uw-import-stats';const errors=(e.rowIssues||[]).filter(x=>x.severity==='ERROR').length;const warns=(e.rowIssues||[]).filter(x=>x.severity==='WARNING').length;for(const [a,b] of [['Qatorlar',(e.rows||[]).length],['Xatolar',errors],['Ogohlantirish',warns]]){const k=doc.createElement('div');k.append(txt(doc,'strong','',b),txt(doc,'small','',a));stats.append(k);}body.append(stats);}
    if(e.busy){const p=doc.createElement('div');p.className='uw-import-progress';p.append(txt(doc,'strong','',e.busyText||'Bajarilmoqda…'));if(e.progressTotal){const bar=doc.createElement('progress');bar.max=e.progressTotal;bar.value=e.progressDone||0;p.append(bar);}body.append(p);}
    const categoryIssues=e.issues||[]; if(categoryIssues.length){const list=doc.createElement('div');list.className='uw-import-errors';categoryIssues.slice(0,20).forEach((it,index)=>{const row=doc.createElement('div');row.append(txt(doc,'span','',`${it.rawName||'Katalog'}${it.targetName?` → ${it.targetName}`:''}`),createButton({label:'Mavjudini tanlash',size:'sm',onClick:()=>excelController.acceptSuggestion(index),disabled:!it.targetCategoryId},doc),createButton({label:'Yangi yaratish',variant:'secondary',size:'sm',onClick:()=>excelController.approveNew(index)},doc));list.append(row);});body.append(list);}
    if(e.result)body.append(createStatePanel({kind:e.result.ok?'empty':e.result.staged?'empty':'error',title:e.result.staged?'Server tekshiruvi tugadi':e.result.ok?'Import tugadi':'Import tugamadi',message:e.result.error||`${e.result.imported||e.result.totalRows||0} ta qator`},doc));
    const foot=doc.createElement('div');foot.className='uw-import-actions';foot.append(createButton({label:e.stagedImport?'Tasdiqlash va katalogga saqlash':'Serverda tekshirish',busy:e.busy,disabled:!(e.rows||[]).length||!!(e.issues||[]).length||!!(e.rowIssues||[]).some(x=>x.severity==='ERROR'),onClick:()=>excelController.process()},doc),createButton({label:'Tozalash',variant:'ghost',disabled:e.busy,onClick:()=>excelController.reset()},doc));if(e.lastBatch?.id)foot.append(createButton({label:'Oxirgi importni bekor qilish',variant:'danger',onClick:async()=>{const ask=confirmAction||((m)=>globalThis.confirm?.(m)===true);if(await ask(`Import #${e.lastBatch.id} bekor qilinsinmi?`))excelController.rollback({confirmed:true});}},doc));body.append(foot);root.append(createCard({title:'Excel orqali import',description:'Preview → server tekshiruvi → tasdiqlash. Import engine yangidan yozilmadi.',body},doc));
  }
  const b=billzController?.getState?.()||{}; if(b.allowed===false){root.append(createStatePanel({kind:'permission',title:'BILLZ uchun ruxsat yo‘q'},doc));return {element:root};}
  const billzBody=doc.createElement('div');billzBody.className='uw-import-panel';const status=txt(doc,'div','uw-billz-status',b.connection?.status||'DISCONNECTED');status.dataset.status=b.connection?.status||'DISCONNECTED';billzBody.append(status);
  if(b.connection?.status!=='CONNECTED'){const secret=createTextField({label:'BILLZ maxfiy integratsiya kaliti',type:'password',autocomplete:'off'},doc);billzBody.append(secret.element,createButton({label:'Ulash',busy:b.busy==='connect',onClick:()=>billzController.connect(secret.input.value)},doc));}
  else {const filters=doc.createElement('div');filters.className='uw-import-filters';const search=createTextField({label:'Qidiruv',value:b.search,placeholder:'BILLZ mahsuloti…'},doc);const cat=createSelectField({label:'BILLZ kategoriyasi',value:b.billzCategoryId||'',options:[{value:'',label:'Barcha kategoriyalar'},...(b.billzCategories||[]).map(c=>({value:c.id,label:c.name}))]},doc);const size=createSelectField({label:'Sahifa',value:String(b.pageSize),options:[10,25,50,100].map(n=>({value:String(n),label:`${n} ta`})).concat([{value:'ALL',label:'Barchasi'}])},doc);search.input.addEventListener('input',()=>billzController.setSearch(search.input.value));cat.select.addEventListener('change',()=>billzController.setBillzCategory(cat.select.value));size.select.addEventListener('change',()=>billzController.setPageSize(size.select.value));filters.append(search.element,cat.element,size.element,createButton({label:'Yangilash',busy:b.busy==='browse',onClick:()=>billzController.browse(1)},doc));billzBody.append(filters);
    if(b.truncated)billzBody.append(createStatePanel({kind:'error',title:'BILLZ katalogi xavfsizlik chegarasiga yetdi',message:'Ro‘yxat qisman bo‘lishi mumkin.'},doc));
    const list=doc.createElement('div');list.className='uw-billz-grid';(b.items||[]).forEach(item=>{const row=doc.createElement('label');row.className='uw-billz-item';const box=doc.createElement('input');box.type='checkbox';box.checked=(b.selectedIds||[]).includes(item.billzProductId);box.addEventListener('change',()=>billzController.toggleSelected(item.billzProductId));const info=doc.createElement('span');info.append(txt(doc,'strong','',item.name),txt(doc,'small','',`${money(item.price)} · Qoldiq ${item.isVariative?item.variants.reduce((s,v)=>s+(Number(v.stock)||0),0):item.stock}`));row.append(box,info);list.append(row);});billzBody.append(list);
    const importControls=doc.createElement('div');importControls.className='uw-import-actions';const target=createSelectField({label:'UStorE katalogi',value:b.targetCategoryId||'',options:[{value:'',label:'Katalogsiz'},...(b.shopCategories||[]).map(c=>({value:c.id,label:c.name}))]},doc);const old=createTextField({label:'Eski narx %',value:b.oldPricePercent||'',placeholder:'20 yoki 10-30'},doc);target.select.addEventListener('change',()=>billzController.setTargetCategory(target.select.value));old.input.addEventListener('input',()=>billzController.setOldPricePercent(old.input.value));importControls.append(target.element,old.element,createButton({label:`Tanlanganlarni import qilish (${(b.selectedIds||[]).length})`,busy:b.busy==='import',disabled:!(b.selectedIds||[]).length,onClick:()=>billzController.importSelected()},doc));billzBody.append(importControls);
    billzBody.append(createButton({label:'BILLZ ulanishini uzish',variant:'danger',onClick:async()=>{const ask=confirmAction||((m)=>globalThis.confirm?.(m)===true);if(await ask('BILLZ ulanishi uzilsinmi?'))billzController.disconnect({confirmed:true});}},doc));
  }
  if(b.error)billzBody.append(createStatePanel({kind:'error',title:'BILLZ amali bajarilmadi',message:b.error.message||'Qayta urinib ko‘ring.'},doc)); root.append(createCard({title:'BILLZ',description:'Secret frontendda saqlanmaydi; server integratsiya actionlari ishlatiladi.',body:billzBody},doc));return {element:root};
}
