const test=require('node:test');const assert=require('node:assert/strict');
const ok=data=>({ok:true,data});const defer=()=>{let r;return{p:new Promise(x=>r=x),resolve:v=>r(v)}};
test('P1G3 router rejects backslashes and control characters',async()=>{const {normalizeInternalTarget}=await import('../../web/navigation/router.js');for(const p of ['/\\evil.test','/a\nb','/a\u0000'])assert.throws(()=>normalizeInternalTarget(p));assert.equal(normalizeInternalTarget('/catalog?q=abc#top'),'/catalog?q=abc#top');});
test('P1G3 portal history and support ignore old selection replies',async()=>{const {createPlatformPortalController}=await import('../../web/features/platform-portal/platform-portal.js');for(const [method,key,field] of [['loadHistory','history','history'],['loadRequestHistory','history','requestHistory'],['openTicket','messages','messages']]){const d=defer();let n=0;const c=createPlatformPortalController({platformPort:{invoke:async()=>++n===1?d.p:ok({[key]:[{id:2}]})}});const a=c[method](1);await c[method](2);d.resolve(ok({[key]:[{id:1}]}));await a;assert.equal(c.getState()[field][0].id,2);}});
test('P1G3 domain optional action exception returns a safe Result',async()=>{const {createDomainsPort}=await import('../../web/services/ports/domains.js');const adapter=Object.fromEntries(['list','add','verify','setPrimary','remove'].map(k=>[k,async()=>ok([])]));adapter.setMiniAppTarget=async()=>{throw Error('private')};const r=await createDomainsPort(adapter).setMiniAppTarget({});assert.equal(r.ok,false);assert.doesNotMatch(r.error.message,/private/);});
test('P1G3 platform and domain replies from a previous account are discarded',async()=>{for(const name of ['platform','domains']){const d=defer();let token='A';const config={endpoint:'https://api.example',botId:'12345',tokenStore:{get:()=>token},fetchImpl:async()=>d.p};const m=await import(`../../web/services/live/${name}.js`);const a=name==='platform'?m.createLivePlatformAdapter(config):m.createLiveDomainsAdapter(config);const pending=name==='platform'?a.invoke('platform_boot'):a.list();token='B';d.resolve({ok:true,status:200,json:async()=>({items:[]})});assert.equal((await pending).error.code,'SESSION_EXPIRED');}});
class N{constructor(){this.children=[];this.dataset={};this.style={};}append(...x){this.children.push(...x)}replaceChildren(...x){this.children=x}setAttribute(){}addEventListener(){}}
test('P1G3 domain refresh keeps newest list and destroy suppresses pending render',async()=>{const {createDomainsFeature}=await import('../../web/features/domains/domains.js');const d=defer();let n=0;const port=Object.fromEntries(['add','verify','setPrimary','remove'].map(k=>[k,async()=>ok({})]));port.list=async()=>++n===1?d.p:ok([]);const f=createDomainsFeature({port,context:{actor:{shopRole:'OWNER'}}},{createElement:()=>new N()});const a=f.load();await f.load();d.resolve(ok([{id:'stale',hostname:'old.example',status:'ACTIVE'}]));await a;assert.deepEqual(f.state.items,[]);f.destroy();const before=n;await f.load();assert.equal(n,before);});
test('P1G3 production domain module exposes a mountable admin page',async()=>{const {createAdminDomainsPage}=await import('../../web/features/domains/index.js');const port=Object.fromEntries(['list','add','verify','setPrimary','remove'].map(k=>[k,async()=>ok([])]));const page=createAdminDomainsPage({services:{domains:port},context:{actor:{shopRole:'OWNER'}},language:'ru'},{createElement:()=>new N()});await page.load();assert.ok(page.element);assert.equal(typeof page.destroy,'function');});
test('P1G3 super-admin details ignore old ticket responses',async()=>{const {createPlatformAdminController}=await import('../../web/features/platform-admin/platform-admin.js');const d=defer();let n=0;const c=createPlatformAdminController({platformPort:{invoke:async action=>action==='platform_boot'?ok({isSuperAdmin:true}):++n===1?d.p:ok({messages:[{id:2}]})}});await c.load();const a=c.openTicket(1);await c.openTicket(2);d.resolve(ok({messages:[{id:1}]}));await a;assert.equal(c.getState().messages[0].id,2);});
