const test=require('node:test');const assert=require('node:assert/strict');
const ok=data=>({ok:true,data});const deferred=()=>{let r;return{p:new Promise(x=>r=x),resolve:v=>r(v)}};
const store=()=>{let v;return{get:()=>v,set:x=>v=structuredClone(x),clear:()=>v=null}};
async function checkout(extra={}){const {createCheckoutSubmitController}=await import('../../web/features/checkout/submit.js');return createCheckoutSubmitController({checkoutIntent:{paymentMethod:'CLICK'},intentStore:store(),ordersPort:{create:async()=>ok({id:'o'})},paymentsPort:{start:async()=>ok({status:'PENDING'}),getStatus:async()=>ok({status:'PAID'})},...extra});}
test('P1G2 reset cannot erase uncertain checkout identity',async()=>{let keys=[];const c=await checkout({ordersPort:{create:async i=>{keys.push(i.idempotencyKey);throw Error('transport')}}});assert.equal((await c.submit()).ok,false);const key=c.getState().idempotencyKey;assert.equal(c.reset().ok,false);await c.retry();assert.deepEqual(keys,[key,key]);});
test('P1G2 reset blocked during request and no duplicate order on double submit',async()=>{const d=deferred();let n=0;const c=await checkout({ordersPort:{create:async()=>{n++;return d.p}}});const a=c.submit(),b=c.submit();assert.equal(c.reset().ok,false);d.resolve(ok({id:'o'}));await Promise.all([a,b]);assert.equal(n,1);});
test('P1G2 recovery is single flight and cannot rewrite a conflicting intent',async()=>{const d=deferred();let n=0;const st=store();st.set({status:'payment-unknown',order:{id:'o'},intentFingerprint:JSON.stringify({paymentMethod:'CLICK'})});const c=await checkout({intentStore:st,paymentsPort:{start:async()=>assert.fail(),getStatus:async()=>{n++;return d.p}}});const a=c.retry(),b=c.recoverPaymentStatus();d.resolve(ok({status:'PAID'}));await Promise.all([a,b]);assert.equal(n,1);st.set({status:'payment-unknown',order:{id:'o'},intentFingerprint:'different'});const conflict=await checkout({intentStore:st});assert.equal((await conflict.recoverPaymentStatus()).ok,false);assert.equal(st.get().intentFingerprint,'different');});
test('P1G2 malformed payment response goes to recovery, never starts again',async()=>{let n=0;const c=await checkout({paymentsPort:{start:async()=>{n++;return ok({})},getStatus:async()=>ok({status:'PAID'})}});assert.equal((await c.submit()).ok,false);assert.equal(c.getState().status,'payment-unknown');await c.retry();assert.equal(n,1);assert.equal(c.getState().status,'success');});
test('P1G2 failed intent persistence prevents dispatch and leaves retryable state',async()=>{let n=0;const c=await checkout({intentStore:{get:()=>null,set(){throw Error('quota')},clear(){}},ordersPort:{create:async()=>{n++;return ok({id:'o'})}}});assert.equal((await c.submit()).ok,false);assert.equal(n,0);assert.equal(c.getState().status,'unknown');});
test('P1G2 service boundary normalizes thrown and malformed replies without leaking details',async()=>{const {createPort}=await import('../../web/services/ports/simple.js');const a=createPort({async invoke(){throw Error('secret')}} ,['invoke'],'admin');assert.equal((await a.invoke()).error.code,'NETWORK_ERROR');assert.doesNotMatch(JSON.stringify(await a.invoke()),/secret/);const b=createPort({async invoke(){return {ok:true}}},['invoke'],'admin');assert.equal((await b.invoke()).error.code,'CONTRACT_MISMATCH');});
test('P1G2 old quote cannot overwrite the latest quote',async()=>{const {createCartController}=await import('../../web/features/cart/cart.js');const d=deferred();let n=0;const c=createCartController({shopId:'s',authenticated:true,cartPort:{load:async()=>ok({shopId:'s',lines:[{productId:'p',quantity:1}]}),quote:async()=>{n++;return n===2?d.p:ok({total:n})}}});await c.load();const old=c.refreshQuote();await c.refreshQuote();d.resolve(ok({total:999}));await old;assert.equal(c.getState().quote.total,3);});
test('P1G2 product double create dispatches one mutation',async()=>{const {createAdminProductEditorController}=await import('../../web/features/admin-products/editor.js');const d=deferred();let n=0;const c=createAdminProductEditorController({actor:{permissions:['products.manage']},adminPort:{invoke:async()=>{n++;return d.p}}});c.openCreate();c.setField('name','Test');c.setField('price','100');const a=c.createProduct(),b=c.createProduct();d.resolve(ok({product:{id:'p',name:'Test',price:100}}));await Promise.all([a,b]);assert.equal(n,1);});
