const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');const root=path.join(__dirname,'..','..');const url=f=>pathToFileURL(path.join(root,f)).href;
function actor(perms=['*']){return{shopRole:'OWNER',permissions:perms};}
function port(){const calls=[];let orders=[{id:1,source:'WEB',user:'Ali',phone:'90',region:'Toshkent',payMethod:'CASH',payableTotal:100,status:'NEW',paymentStatus:'PENDING',createdAt:'2026-09-22T08:00:00Z'},{id:2,source:'TELEGRAM',user:'Vali',phone:'91',region:'Samarqand',payMethod:'CLICK',payableTotal:200,status:'PROCESSING',paymentStatus:'PAID',createdAt:'2026-09-21T08:00:00Z'}];return{calls,api:{async invoke(action,payload={}){calls.push({action,payload:structuredClone(payload)});if(action==='get_all_orders')return{ok:true,data:{orders:structuredClone(orders)}};if(action==='update_order_status'){const row=orders.find(x=>x.id===payload.orderId);if(!row)return{ok:false,error:{code:'NOT_FOUND',message:'no',retryable:false}};row.status=payload.newStatus;return{ok:true,data:{order:structuredClone(row)}};}return{ok:false,error:{code:'CAPABILITY_UNAVAILABLE',message:'no',retryable:false}};}}};}
test('K1 normalizes order source and permission-aware status actions',async()=>{const m=await import(url('web/features/admin-orders/orders.js'));assert.equal(m.normalizeAdminOrder({id:1,order_source:'WEB',status:'NEW'}).source,'WEB');assert.equal(m.normalizeAdminOrder({id:2,source:'OTHER'}).source,'UNKNOWN');assert.deepEqual(m.adminOrderActionAvailability(actor(['orders.manage']),{status:'NEW'}).nextStatuses,['PROCESSING','CANCELLED']);assert.equal(m.adminOrderActionAvailability(actor(['orders.view']),{status:'NEW'}).nextStatuses.length,0);});
test('K1 loads, filters and updates order status through reviewed admin actions',async()=>{const {createAdminOrdersController}=await import(url('web/features/admin-orders/orders.js'));const p=port();const c=createAdminOrdersController({adminPort:p.api,actor:actor()});assert.equal((await c.load()).ok,true);c.setFilter('source','WEB');assert.equal(c.getState().items.length,1);assert.equal(c.open('1').ok,true);const r=await c.updateStatus('1','PROCESSING');assert.equal(r.ok,true);assert.equal(c.getState().all.find(x=>x.id==='1').status,'PROCESSING');assert.ok(p.calls.some(x=>x.action==='update_order_status'));});
test('K1 denies status mutation without orders.manage before network',async()=>{const {createAdminOrdersController}=await import(url('web/features/admin-orders/orders.js'));const p=port();const c=createAdminOrdersController({adminPort:p.api,actor:actor(['orders.view'])});await c.load();const before=p.calls.length;const r=await c.updateStatus('1','PROCESSING');assert.equal(r.ok,false);assert.equal(r.error.code,'FORBIDDEN');assert.equal(p.calls.length,before);});
test('K1 live/server whitelist includes status mutation with orders.manage',()=>{const live=fs.readFileSync(path.join(root,'web/services/live/admin.js'),'utf8');const api=fs.readFileSync(path.join(root,'supabase/functions/shop-api/index.ts'),'utf8');assert.match(live,/'get_all_orders'/);assert.match(live,/'update_order_status'/);assert.match(api,/update_order_status: 'orders\.manage'/);assert.match(api,/case "update_order_status"[\s\S]*requirePermission\('orders\.manage'\)/);});
test('K1 admin route has deep detail path and admin shell keeps permission gate',()=>{const routes=fs.readFileSync(path.join(root,'web/navigation/routes.js'),'utf8');const shell=fs.readFileSync(path.join(root,'web/shells/admin.js'),'utf8');assert.match(routes,/\/admin\/orders\/:orderId/);assert.match(shell,/label: 'Buyurtmalar'[\s\S]*permission: 'orders\.view'/);});
test('K1 source contains desktop table, mobile cards, filters and source chip text',()=>{const ui=fs.readFileSync(path.join(root,'web/features/admin-orders/orders.js'),'utf8');const css=fs.readFileSync(path.join(root,'web/styles/features.css'),'utf8');for(const phrase of ['Buyurtmalar','#ID, mijoz yoki telefon','Manba','To‘lov'])assert.match(ui,new RegExp(phrase));assert.match(ui,/uw-admin-orders-table/);assert.match(ui,/uw-admin-orders-cards/);assert.match(css,/uw-admin-orders-table-wrap/);assert.match(css,/max-width:63\.999rem/);});
