const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');const root=path.join(__dirname,'..','..');const url=f=>pathToFileURL(path.join(root,f)).href;
function actor(perms=['*']){return{shopRole:'OWNER',permissions:perms};}
function makePort(){const calls=[];let rows=[{key:'p1:',productId:'p1',productName:'Protein',productSku:'SKU1',variantSku:null,stock:2,state:'LOW_STOCK',manageable:true},{key:'p2:V1',productId:'p2',productName:'Kiyim',productSku:'P2',variantSku:'V1',color:'Qora',size:'M',stock:4,state:'LOW_STOCK',manageable:true}];let movements=[];return{calls,api:{async invoke(action,payload={}){calls.push({action,payload:structuredClone(payload)});if(action==='get_inventory_rows')return{ok:true,data:{rows:structuredClone(rows),lowStockThreshold:5}};if(action==='get_stock_movements')return{ok:true,data:{movements:structuredClone(movements),total:movements.length}};if(action==='bulk_stock_update'){const u=payload.updates[0];const row=rows.find(x=>(x.variantSku||x.productSku)===u.sku);const prior=row.stock;row.stock=u.stock;movements.unshift({operationType:'MANUAL',productName:row.productName,variantSku:row.variantSku,priorStock:prior,delta:u.stock-prior,newStock:u.stock});return{ok:true,data:{products:[{}],errors:[]}};}if(action==='record_stock_in'){const row=rows.find(x=>x.productId===payload.productId&&String(x.variantSku||'')===String(payload.variantSku||''));const prior=row.stock;row.stock+=payload.qty;movements.unshift({operationType:'KIRIM',productName:row.productName,variantSku:row.variantSku,priorStock:prior,delta:payload.qty,newStock:row.stock});return{ok:true,data:{product:{}}};}return{ok:false,error:{code:'CAPABILITY_UNAVAILABLE',message:'no',retryable:false}};}}};}
test('K2 normalizes variant row state and separates view/manage permissions',async()=>{const m=await import(url('web/features/admin-inventory/inventory.js'));assert.equal(m.normalizeInventoryRow({productId:'p',stock:0},5).state,'OUT_OF_STOCK');assert.equal(m.normalizeInventoryRow({productId:'p',stock:3},5).state,'LOW_STOCK');assert.deepEqual(m.inventoryActionAvailability(actor(['stock.view'])),{canView:true,canManage:false});});
test('K2 loads variant inventory + history and server confirms exact stock before reload',async()=>{const {createAdminInventoryController}=await import(url('web/features/admin-inventory/inventory.js'));const p=makePort();const c=createAdminInventoryController({adminPort:p.api,actor:actor()});assert.equal((await c.load()).ok,true);assert.equal(c.getState().rows.length,2);assert.equal((await c.setExactStock('p2:V1',7)).ok,true);assert.equal(c.getState().rows.find(x=>x.key==='p2:V1').stock,7);assert.ok(p.calls.some(x=>x.action==='bulk_stock_update'));});
test('K2 + Kirim preserves variant SKU and movement history',async()=>{const {createAdminInventoryController}=await import(url('web/features/admin-inventory/inventory.js'));const p=makePort();const c=createAdminInventoryController({adminPort:p.api,actor:actor()});await c.load();const r=await c.recordStockIn('p2:V1',3);assert.equal(r.ok,true);const call=p.calls.find(x=>x.action==='record_stock_in');assert.deepEqual(call.payload,{productId:'p2',variantSku:'V1',qty:3});assert.equal(c.getState().movements[0].newStock,7);});
test('K2 stock.view can read but cannot mutate before network',async()=>{const {createAdminInventoryController}=await import(url('web/features/admin-inventory/inventory.js'));const p=makePort();const c=createAdminInventoryController({adminPort:p.api,actor:actor(['stock.view'])});await c.load();const before=p.calls.length;const r=await c.setExactStock('p1:',9);assert.equal(r.ok,false);assert.equal(r.error.code,'FORBIDDEN');assert.equal(p.calls.length,before);});
test('K2 live/server expose narrow stock actions and variant KIRIM ledger uses variant prior/new values',()=>{const live=fs.readFileSync(path.join(root,'web/services/live/admin.js'),'utf8');const api=fs.readFileSync(path.join(root,'supabase/functions/shop-api/index.ts'),'utf8');for(const a of ['get_inventory_rows','bulk_stock_update','record_stock_in','get_stock_movements'])assert.match(live,new RegExp(`'${a}'`));assert.match(api,/get_inventory_rows: 'stock\.view'/);assert.match(api,/bulk_stock_update: 'stock\.manage'/);assert.match(api,/movementPriorStock = Number\(matched\.qty\)/);assert.match(api,/new_stock: movementNewStock/);});
test('K2 route/nav and namespaced responsive styles are restored',()=>{const routes=fs.readFileSync(path.join(root,'web/navigation/routes.js'),'utf8');const shell=fs.readFileSync(path.join(root,'web/shells/admin.js'),'utf8');const css=fs.readFileSync(path.join(root,'web/styles/features.css'),'utf8');assert.match(routes,/\/admin\/inventory/);assert.match(shell,/label: 'Ombor'[\s\S]*permission: 'stock\.view'/);assert.match(css,/uw-admin-inventory-table-wrap/);assert.match(css,/uw-inventory-history/);});
