import { scrollElementIntoView } from '../../a11y/preferences.js';
import { createButton, createStatePanel } from '../../components/ui.js';

function getDocument(documentRef) {
  const doc = documentRef || globalThis.document;
  if (!doc?.createElement) throw new Error('document kerak');
  return doc;
}
function clone(value) { return value == null ? value : JSON.parse(JSON.stringify(value)); }
function money(value) { return `${new Intl.NumberFormat('uz-UZ').format(Number(value || 0))} so‘m`; }
function date(value) { if (!value) return '—'; const d=new Date(value); return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('uz-UZ',{day:'2-digit',month:'short',year:'numeric'}).format(d); }
function dateTime(value) { if (!value) return '—'; const d=new Date(value); return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('uz-UZ',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(d); }
function daysUntil(value) { if (!value) return null; const ms=new Date(value).getTime()-Date.now(); return Number.isFinite(ms)?Math.ceil(ms/86400000):null; }
function normalizeList(value) { return Array.isArray(value) ? value.filter(Boolean) : []; }
function safeUrl(value) { try { const u=new URL(String(value||'')); return ['https:','http:'].includes(u.protocol) ? u.href : ''; } catch { return ''; } }
function escapeLabel(value, fallback='—') { const s=String(value??'').trim(); return s || fallback; }
function normalizeTariff(row) { if(!row||!row.id)return null; return {id:String(row.id),name:escapeLabel(row.name,'Tarif'),price:Number(row.price||0),productLimit:row.productLimit==null?null:Number(row.productLimit),isPopular:row.isPopular===true,features:normalizeList(row.features).map(String)}; }
function normalizeShop(row) { if(!row||!row.id)return null; return {...row,id:String(row.id),status:String(row.status||'UNKNOWN').toUpperCase(),shopName:row.shopName||null,botUsername:row.botUsername||null,tariffId:row.tariffId||null,tariffName:row.tariffName||null,productLimit:row.productLimit==null?null:Number(row.productLimit),usedProductCount:Number(row.usedProductCount||0),usedOrderCount:Number(row.usedOrderCount||0),ordersToday:Number(row.ordersToday||0)}; }
function normalizeRequest(row) { if(!row||!row.id)return null; return {...row,id:String(row.id),kind:String(row.kind||''),status:String(row.status||'').toUpperCase(),tariffPrice:Number(row.tariffPrice||0),durationDays:Number(row.durationDays||0)}; }
function statusTone(status) { const s=String(status||'').toUpperCase(); if(['ACTIVE','APPROVED','ANSWERED'].includes(s))return 'success'; if(['FROZEN','NEW','PROVISIONING','PENDING'].includes(s))return 'warning'; if(['TERMINATED','REJECTED','ERROR','CLOSED'].includes(s))return 'danger'; return 'neutral'; }
function statusLabel(status) { const s=String(status||'').toUpperCase(); return ({ACTIVE:'Faol',FROZEN:'Muzlatilgan',TERMINATED:"O‘chirilgan",NEW:'Tekshirilmoqda',APPROVED:'Tasdiqlangan',REJECTED:'Rad etilgan',OPEN:'Ochiq',ANSWERED:'Javob berilgan',CLOSED:'Yopilgan',PROVISIONING:'Tayyorlanmoqda'})[s]||s||'Noma’lum'; }
function requestKindLabel(row) { if(row?.kind==='NEW_SHOP')return "Yangi do‘kon"; if(row?.upgradeAction==='EXTEND')return 'Obunani uzaytirish'; if(row?.kind==='UPGRADE')return "Tarifni o‘zgartirish"; return 'Ariza'; }
function subscriptionExpiryLabel(shop) { const d=daysUntil(shop?.subscriptionExpiresAt); if(d==null)return 'Muddat noma’lum'; if(d<=0)return 'Obuna tugagan'; return `${d} kun qoldi`; }
function createStore(initial) {
  let state=Object.freeze(initial); const listeners=new Set();
  return {get:()=>state,set:(patch)=>{state=Object.freeze({...state,...patch});for(const fn of listeners)fn(state);return state;},subscribe:(fn)=>{listeners.add(fn);return()=>listeners.delete(fn);}};
}
async function fileToBase64(file) {
  if (!file) return null;
  if (typeof FileReader === 'undefined') throw new Error('Brauzer fayl o‘qishni qo‘llamaydi.');
  return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||'').split(',')[1]||'');reader.onerror=()=>reject(new Error("Faylni o‘qib bo‘lmadi."));reader.readAsDataURL(file);});
}
function validateImage(file) {
  if(!file)return null;
  if(!/^image\/(jpeg|png|webp)$/i.test(String(file.type||'')))return 'Faqat JPG, PNG yoki WebP rasm qabul qilinadi.';
  if(Number(file.size||0)>6*1024*1024)return 'Rasm hajmi 6 MB dan katta bo‘lmasin.';
  return null;
}

export function createPlatformPortalController({ platformPort, authPort = null, sessionStorage=globalThis.sessionStorage } = {}) {
  if(!platformPort?.invoke)throw new TypeError('platformPort kerak');
  const store=createStore({
    status:'idle',error:null,actor:null,isSuperAdmin:false,shops:[],requests:[],tariffs:[],lifecycleSettings:{},
    selectedShopId:null,historyStatus:'idle',history:[],selectedRequestId:null,requestHistoryStatus:'idle',requestHistory:[],
    supportStatus:'idle',tickets:[],selectedTicketId:null,messages:[],supportError:null,
    checkout:null,checkoutStatus:'idle',checkoutError:null,paymentInfo:null,paymentMethods:[],changePreview:null,
    mutationStatus:null,notice:null,
  });
  let shopView=0, requestView=0, ticketView=0, checkoutPending=null;
  const invoke=(action,payload={})=>platformPort.invoke(action,payload);
  const setNotice=(kind,message)=>store.set({notice:message?{kind,message}:null});
  async function refreshBoot({preserveSelection=true}={}) {
    store.set({status:'loading',error:null});
    const result=await invoke('platform_boot',{});
    if(!result.ok){store.set({status:'error',error:result.error||{message:'Platforma yuklanmadi.'}});return result;}
    const shops=normalizeList(result.data?.myShops).map(normalizeShop).filter(Boolean);
    const requests=normalizeList(result.data?.myRequests).map(normalizeRequest).filter(Boolean);
    const tariffs=normalizeList(result.data?.tariffs).map(normalizeTariff).filter(Boolean);
    const previous=store.get();
    const selectedShopId=preserveSelection&&shops.some(s=>s.id===previous.selectedShopId)?previous.selectedShopId:(shops[0]?.id||null);
    store.set({status:'ready',error:null,actor:result.data?.platformActor||null,isSuperAdmin:result.data?.isSuperAdmin===true,shops,requests,tariffs,lifecycleSettings:result.data?.lifecycleSettings||{},selectedShopId});
    return result;
  }
  async function refreshRequests(){const r=await invoke('platform_list_my_subscription_requests',{});if(r.ok)store.set({requests:normalizeList(r.data?.requests).map(normalizeRequest).filter(Boolean)});return r;}
  async function refreshShops(){const r=await invoke('platform_list_my_shops',{});if(r.ok){const shops=normalizeList(r.data?.myShops).map(normalizeShop).filter(Boolean);const cur=store.get().selectedShopId;store.set({shops,selectedShopId:shops.some(s=>s.id===cur)?cur:(shops[0]?.id||null)});}return r;}
  async function loadHistory(shopId){const view=++shopView;const id=String(shopId||'');if(!id)return {ok:false,error:{code:'VALIDATION_ERROR',message:'Do‘kon tanlanmagan.'}};store.set({selectedShopId:id,historyStatus:'loading',history:[]});const r=await invoke('platform_list_my_subscription_history',{shopId:id});if(view!==shopView)return r;if(r.ok)store.set({historyStatus:'ready',history:normalizeList(r.data?.history)});else store.set({historyStatus:'error',history:[]});return r;}
  async function loadRequestHistory(requestId){const view=++requestView;const id=String(requestId||'');store.set({selectedRequestId:id,requestHistoryStatus:'loading',requestHistory:[]});const r=await invoke('platform_get_subscription_request_history',{requestId:id});if(view!==requestView)return r;if(r.ok)store.set({requestHistoryStatus:'ready',requestHistory:normalizeList(r.data?.history)});else store.set({requestHistoryStatus:'error',requestHistory:[]});return r;}
  async function loadSupport(){store.set({supportStatus:'loading',supportError:null});const [a,b]=await Promise.all([invoke('platform_get_my_support_tickets',{type:'SUPPORT'}),invoke('platform_get_my_support_tickets',{type:'BUG_REPORT'})]);if(!a.ok&&!b.ok){store.set({supportStatus:'error',supportError:a.error||b.error,tickets:[]});return a;}
    const tickets=[...(a.ok?normalizeList(a.data?.tickets):[]),...(b.ok?normalizeList(b.data?.tickets):[])].sort((x,y)=>Number(y.id||0)-Number(x.id||0));store.set({supportStatus:'ready',tickets});return {ok:true,data:{tickets}};}
  async function openTicket(ticketId){const view=++ticketView;const id=Number(ticketId);store.set({selectedTicketId:id,supportStatus:'loading',supportError:null,messages:[]});const r=await invoke('platform_get_support_messages',{ticketId:id});if(view!==ticketView)return r;if(r.ok)store.set({supportStatus:'ready',messages:normalizeList(r.data?.messages)});else store.set({supportStatus:'error',supportError:r.error,messages:[]});return r;}
  async function createTicket({type='SUPPORT',message='',subject='',pageContext='',file=null}={}){const text=String(message||'').trim();if(!text)return {ok:false,error:{code:'VALIDATION_ERROR',message:'Xabarni kiriting.'}};const fileError=validateImage(file);if(fileError)return {ok:false,error:{code:'VALIDATION_ERROR',message:fileError}};store.set({mutationStatus:'support-create'});try{let attachmentUpload; if(file){attachmentUpload={base64:await fileToBase64(file),mimeType:file.type,fileName:file.name};}const r=await invoke('platform_create_support_ticket',{type:type==='BUG_REPORT'?'BUG_REPORT':'SUPPORT',message:text,subject:String(subject||'').trim()||undefined,pageContext:String(pageContext||'').trim()||undefined,attachmentUpload});if(r.ok){setNotice('success','Murojaat yuborildi.');await loadSupport();if(r.data?.ticketId)await openTicket(r.data.ticketId);}return r;}finally{store.set({mutationStatus:null});}}
  async function sendSupportMessage(ticketId,body){const text=String(body||'').trim();if(!text)return {ok:false,error:{code:'VALIDATION_ERROR',message:'Xabarni kiriting.'}};store.set({mutationStatus:'support-send'});try{const r=await invoke('platform_send_support_message',{ticketId:Number(ticketId),body:text});if(r.ok){await openTicket(ticketId);await loadSupport();}return r;}finally{store.set({mutationStatus:null});}}
  async function closeTicket(ticketId){store.set({mutationStatus:'support-close'});try{const r=await invoke('platform_close_support_ticket',{ticketId:Number(ticketId)});if(r.ok){await loadSupport();store.set({selectedTicketId:null,messages:[]});}return r;}finally{store.set({mutationStatus:null});}}

  async function loadPaymentOptions(){const [card,methods]=await Promise.all([invoke('platform_get_payment_info',{}),invoke('platform_list_payment_methods',{})]);store.set({paymentInfo:card.ok?card.data:null,paymentMethods:methods.ok?normalizeList(methods.data?.methods):[]});return {ok:card.ok||methods.ok};}
  function beginCheckout(config={}){
    const state=store.get(); const kind=config.kind==='UPGRADE'?'UPGRADE':'NEW_SHOP'; const shop=state.shops.find(s=>s.id===String(config.shopId||''));
    const defaultTariffId=String(config.tariffId||shop?.tariffId||state.tariffs[0]?.id||'');
    store.set({checkout:{kind,shopId:shop?.id||null,upgradeAction:kind==='UPGRADE'?(config.upgradeAction||'CHANGE'):null,tariffId:defaultTariffId,billingPeriod:config.billingPeriod==='annual'?'annual':'monthly',shopName:String(config.shopName||''),ownerTelegramId:String(config.ownerTelegramId||''),botName:String(config.botName||''),botBio:String(config.botBio||''),paymentMethod:null,paymentMethodId:null,externalOpened:false,consentAccepted:false,preparedRequestId:config.preparedRequestId||null,paymentDeadlineAt:config.paymentDeadlineAt||null,receiptFile:null},checkoutStatus:'editing',checkoutError:null,changePreview:null,notice:null});
    loadPaymentOptions(); if(kind==='UPGRADE'&&config.upgradeAction==='CHANGE'&&shop?.id&&defaultTariffId)loadChangePreview(shop.id,defaultTariffId,config.billingPeriod==='annual'?'annual':'monthly'); return store.get().checkout;
  }
  function patchCheckout(patch={}){if(checkoutPending)return store.get().checkout;const current=store.get().checkout;if(!current)return null;if(current.submittedRequestId)patch={...(Object.hasOwn(patch,'receiptFile')?{receiptFile:patch.receiptFile}:{})};const next={...current,...patch};store.set({checkout:next,checkoutError:null});if(next.kind==='UPGRADE'&&next.upgradeAction==='CHANGE'&&next.shopId&&next.tariffId)loadChangePreview(next.shopId,next.tariffId,next.billingPeriod);return next;}
  async function loadChangePreview(shopId,tariffId,billingPeriod){const key=`${shopId}:${tariffId}:${billingPeriod}`;store.set({changePreview:{key,status:'loading',data:null}});const r=await invoke('platform_preview_tariff_change',{shopId,tariffId,billingPeriod});if(store.get().changePreview?.key!==key)return r;store.set({changePreview:r.ok?{key,status:'ready',data:r.data}:{key,status:'error',data:null}});return r;}
  async function prepareNewShopDraft(){const c=store.get().checkout;if(!c||c.kind!=='NEW_SHOP')return {ok:false,error:{code:'VALIDATION_ERROR',message:'Yangi do‘kon oqimi ochilmagan.'}};if(String(c.shopName||'').trim().length<2)return {ok:false,error:{code:'VALIDATION_ERROR',message:'Do‘kon nomini kiriting.'}};if(!/^\d{5,15}$/.test(String(c.ownerTelegramId||'')))return {ok:false,error:{code:'VALIDATION_ERROR',message:'Owner Telegram ID noto‘g‘ri.'}};store.set({checkoutStatus:'preparing',checkoutError:null});const r=await invoke('platform_prepare_subscription_request',{kind:'NEW_SHOP',requestId:c.preparedRequestId||undefined,tariffId:c.tariffId,billingPeriod:c.billingPeriod,shopName:String(c.shopName).trim(),ownerTelegramId:String(c.ownerTelegramId),botName:String(c.botName||'').trim()||undefined,botBio:String(c.botBio||'').trim()||undefined});if(r.ok)patchCheckout({preparedRequestId:r.data?.requestId||c.preparedRequestId,paymentDeadlineAt:r.data?.paymentDeadlineAt||null});store.set({checkoutStatus:r.ok?'editing':'error',checkoutError:r.ok?null:r.error});return r;}
  function selectExternalPayment(methodId){const c=store.get().checkout;if(!c)return null;const method=store.get().paymentMethods.find(m=>String(m.id)===String(methodId));return patchCheckout({paymentMethod:String(method?.methodType||'').toUpperCase(),paymentMethodId:method?.id||null,externalOpened:false});}
  function selectCardPayment(){return patchCheckout({paymentMethod:'CARD',paymentMethodId:null,externalOpened:true});}
  async function submitCheckoutInternal(){const c=store.get().checkout;if(!c)return {ok:false,error:{code:'VALIDATION_ERROR',message:'To‘lov oqimi ochilmagan.'}};
    if(!c.tariffId)return {ok:false,error:{code:'VALIDATION_ERROR',message:'Tarif tanlanmagan.'}}; if(!c.paymentMethod)return {ok:false,error:{code:'VALIDATION_ERROR',message:'To‘lov usulini tanlang.'}}; if(!c.consentAccepted)return {ok:false,error:{code:'VALIDATION_ERROR',message:'Shartlar va maxfiylik siyosatiga rozilik kerak.'}};
    if(c.paymentMethod!=='CARD'&&!c.externalOpened)return {ok:false,error:{code:'VALIDATION_ERROR',message:'Avval to‘lov sahifasini oching.'}};
    if(c.kind==='NEW_SHOP'){if(String(c.shopName||'').trim().length<2)return {ok:false,error:{code:'VALIDATION_ERROR',message:'Do‘kon nomini kiriting.'}};if(!/^\d{5,15}$/.test(String(c.ownerTelegramId||'')))return {ok:false,error:{code:'VALIDATION_ERROR',message:'Owner Telegram ID noto‘g‘ri.'}};}
    const fileError=validateImage(c.receiptFile);if(fileError)return {ok:false,error:{code:'VALIDATION_ERROR',message:fileError}};
    store.set({checkoutStatus:'submitting',checkoutError:null});try{let receiptImageUpload; if(c.receiptFile)receiptImageUpload={base64:await fileToBase64(c.receiptFile),mimeType:c.receiptFile.type,fileName:c.receiptFile.name};const payload={kind:c.kind,shopId:c.shopId||undefined,tariffId:c.tariffId,requestId:c.kind==='NEW_SHOP'?(c.preparedRequestId||undefined):undefined,billingPeriod:c.billingPeriod,upgradeAction:c.upgradeAction||undefined,paymentMethod:c.paymentMethod,paymentMethodId:c.paymentMethodId||undefined,consentAccepted:true,shopName:c.kind==='NEW_SHOP'?String(c.shopName).trim():undefined,ownerTelegramId:c.kind==='NEW_SHOP'?String(c.ownerTelegramId):undefined,botName:c.kind==='NEW_SHOP'?(String(c.botName||'').trim()||undefined):undefined,botBio:c.kind==='NEW_SHOP'?(String(c.botBio||'').trim()||undefined):undefined,receiptImageUpload};const {receiptImageUpload:receipt,...submission}=payload;
      const storageKey=`ustore:subscription:${String(store.get().actor?.accountId||store.get().actor?.telegramId||store.get().actor?.id||'current')}:${JSON.stringify(submission)}`;
      let submissionKey=c.submissionKey;try{submissionKey=submissionKey||sessionStorage?.getItem(storageKey);}catch{}
      submissionKey=submissionKey||globalThis.crypto.randomUUID();store.set({checkout:{...c,submissionKey}});try{sessionStorage?.setItem(storageKey,submissionKey);}catch{}
      const r=await invoke('platform_submit_subscription_request',{...submission,submissionKey});
      if(!r.ok){store.set({checkoutStatus:'error',checkoutError:r.error});return r;}
      const requestId=r.data?.requestId;if(!requestId){const error={code:'CONTRACT_MISMATCH',message:'Ariza ID qaytmadi.'};store.set({checkoutStatus:'error',checkoutError:error});return {ok:false,error};}
      store.set({checkout:{...store.get().checkout,submittedRequestId:requestId}});
      if(r.data.status!=='NEW'){store.set({checkoutStatus:'submitted',checkoutError:null});}
      else if(receipt&&!r.data.hasReceipt){const attached=await invoke('platform_attach_request_receipt',{requestId,receiptImageUpload:receipt,source:'PAYMENT_PAGE'});if(!attached.ok){store.set({checkoutStatus:'receipt-warning',checkoutError:attached.error});await refreshRequests();return r;}store.set({checkoutStatus:'submitted',checkoutError:null});}
      else if(!r.data.paymentClaimedAt){const claim=await invoke('platform_confirm_payment_claim',{requestId});if(!claim.ok){store.set({checkoutStatus:'claim-warning',checkoutError:claim.error});await refreshRequests();return r;}store.set({checkoutStatus:'submitted',checkoutError:null});}
      else store.set({checkoutStatus:'submitted',checkoutError:null});
      try{sessionStorage?.removeItem(storageKey);}catch{}
      await Promise.all([refreshRequests(),refreshShops()]);setNotice('success','Ariza yuborildi. Holatini “Arizalarim”da kuzatishingiz mumkin.');return r;}catch(error){const e={code:'NETWORK_ERROR',message:error?.message||'So‘rov yuborilmadi.'};store.set({checkoutStatus:'error',checkoutError:e});return {ok:false,error:e};}}
  function submitCheckout(){if(checkoutPending)return checkoutPending;checkoutPending=Promise.resolve().then(submitCheckoutInternal).finally(()=>{checkoutPending=null;});return checkoutPending;}
  async function retryPaymentClaim(requestId){store.set({mutationStatus:'claim'});try{const r=await invoke('platform_confirm_payment_claim',{requestId:String(requestId)});if(r.ok){await refreshRequests();setNotice('success','To‘lov vaqti serverda qayd etildi.');}return r;}finally{store.set({mutationStatus:null});}}
  async function attachRequestReceipt(requestId,file){const err=validateImage(file);if(err)return {ok:false,error:{code:'VALIDATION_ERROR',message:err}};store.set({mutationStatus:'receipt'});try{const receiptImageUpload={base64:await fileToBase64(file),mimeType:file.type,fileName:file.name};const r=await invoke('platform_attach_request_receipt',{requestId:String(requestId),receiptImageUpload,source:'MY_REQUESTS'});if(r.ok){await Promise.all([refreshRequests(),loadRequestHistory(requestId)]);setNotice('success','Chek yuborildi.');}return r;}finally{store.set({mutationStatus:null});}}
  function resumeRequest(requestId){const r=store.get().requests.find(x=>x.id===String(requestId));if(!r||r.kind!=='NEW_SHOP'||r.status!=='NEW'||r.paymentClaimedAt)return null;return beginCheckout({kind:'NEW_SHOP',tariffId:r.tariffId,billingPeriod:r.billingPeriod==='ANNUAL'?'annual':'monthly',shopName:r.requestedShopName||'',ownerTelegramId:r.ownerTelegramId||'',botName:r.requestedBotName||'',botBio:r.requestedBotBio||'',preparedRequestId:r.id,paymentDeadlineAt:r.paymentDeadlineAt||null});}
  function cancelCheckout(){if(checkoutPending)return;store.set({checkout:null,checkoutStatus:'idle',checkoutError:null,changePreview:null});}
  async function signOut(){if(!authPort?.signOut)return {ok:false,error:{code:'UNAVAILABLE',message:'Chiqish mavjud emas.'}};const r=await authPort.signOut();if(r.ok)store.set({status:'idle',actor:null,shops:[],requests:[],tariffs:[]});return r;}
  return Object.freeze({
    getState:store.get,subscribe:store.subscribe,load:refreshBoot,refreshBoot,refreshRequests,refreshShops,loadHistory,loadRequestHistory,
    loadSupport,openTicket,createTicket,sendSupportMessage,closeTicket,beginCheckout,patchCheckout,prepareNewShopDraft,selectExternalPayment,selectCardPayment,submitCheckout,retryPaymentClaim,attachRequestReceipt,resumeRequest,cancelCheckout,signOut,setNotice,
  });
}

function el(doc,tag,className,text){const n=doc.createElement(tag);if(className)n.className=className;if(text!=null)n.textContent=String(text);return n;}
function badge(doc,label,tone='neutral'){const n=el(doc,'span',`uw-platform-badge uw-platform-badge--${tone}`,label);return n;}
function iconLetter(doc,label){const n=el(doc,'span','uw-platform-mini-icon',String(label||'U').slice(0,1).toUpperCase());n.setAttribute('aria-hidden','true');return n;}
function platformPath(section,id=''){const base=`/platform/${section}`;return id?`${base}/${encodeURIComponent(id)}`:base;}

function portalHeader(doc,state,{onNavigate,onLogout}){
  const head=el(doc,'header','uw-platform-portal__header');
  const brand=el(doc,'button','uw-platform-portal__brand');brand.type='button';brand.append(iconLetter(doc,'U'),el(doc,'strong','', 'UStorE'));brand.addEventListener('click',()=>onNavigate?.('/platform/app'));
  const right=el(doc,'div','uw-platform-portal__header-actions');
  const actor=el(doc,'div','uw-platform-actor');const name=el(doc,'strong','',state.actor?.displayName||'UStorE foydalanuvchi');const role=el(doc,'small','',state.isSuperAdmin?'SUPER ADMIN':'Platforma akkaunti');actor.append(name,role);
  const logout=createButton({label:'Chiqish',variant:'ghost',size:'sm',onClick:onLogout},doc);right.append(actor,logout);head.append(brand,right);return head;
}
const NAV=[['app','Bosh sahifa','/platform/app'],['shops',"Do‘konlar",'/platform/shops'],['subscriptions','Obunalar','/platform/subscriptions'],['requests','Arizalar','/platform/requests'],['support','Yordam','/platform/support'],['profile','Profil','/platform/profile']];
function portalNav(doc,active,onNavigate,state={}){const nav=el(doc,'nav','uw-platform-portal__nav');nav.setAttribute('aria-label','Platforma bo‘limlari');for(const [id,label,href] of NAV){const a=el(doc,'a',id===active?'is-active':'',label);a.href=href;a.addEventListener('click',(e)=>{e.preventDefault?.();onNavigate?.(href);});nav.append(a);}if(state.isSuperAdmin===true){const a=el(doc,'a','uw-platform-portal__admin-link','Super Admin');a.href='/platform/admin';a.addEventListener('click',(e)=>{e.preventDefault?.();onNavigate?.('/platform/admin');});nav.append(a);}return nav;}
function pageHeading(doc,title,subtitle,action){const row=el(doc,'div','uw-platform-page-head');const copy=el(doc,'div');copy.append(el(doc,'h1','',title),el(doc,'p','',subtitle));row.append(copy);if(action)row.append(action);return row;}
function statePanelFor(doc,state,onRetry){if(state.status==='loading'||state.status==='idle')return createStatePanel({kind:'loading',title:'Platforma yuklanmoqda',message:'Do‘konlar, obuna va arizalar serverdan olinmoqda.'},doc);if(state.status==='error')return createStatePanel({kind:'error',title:'Platforma yuklanmadi',message:state.error?.message||'Server bilan ulanishda xato.',actionLabel:'Qayta urinish',onAction:onRetry},doc);return null;}

function overviewView(doc,state,onNavigate,controller){
  const wrap=el(doc,'div','uw-platform-page');wrap.append(pageHeading(doc,'Boshqaruv markazi','Do‘konlaringiz, obuna va murojaatlaringizning serverdagi joriy holati.'));
  const grid=el(doc,'div','uw-platform-stat-grid');const active=state.shops.filter(s=>s.status==='ACTIVE').length;const openReq=state.requests.filter(r=>r.status==='NEW').length;const exp=state.shops.map(s=>daysUntil(s.subscriptionExpiresAt)).filter(v=>v!=null&&v>=0).sort((a,b)=>a-b)[0];
  for(const [label,value,meta] of [["Do‘konlar",state.shops.length,`${active} ta faol`],['Faol arizalar',openReq,'Tekshiruvdagi so‘rovlar'],['Eng yaqin obuna',exp==null?'—':`${exp} kun`,'Tugashigacha']]){const c=el(doc,'article','uw-platform-stat');c.append(el(doc,'small','',label),el(doc,'strong','',value),el(doc,'span','',meta));grid.append(c);}wrap.append(grid);
  const cards=el(doc,'div','uw-platform-dashboard-grid');
  const shopsCard=el(doc,'section','uw-platform-card');shopsCard.append(el(doc,'h2','',"Do‘konlarim"));if(!state.shops.length)shopsCard.append(el(doc,'p','uw-muted',"Hozircha do‘kon yo‘q. Tarif tanlab yangi do‘kon arizasini yuborishingiz mumkin."));else{for(const s of state.shops.slice(0,3)){const r=el(doc,'button','uw-platform-list-row');r.type='button';r.addEventListener('click',()=>onNavigate?.(platformPath('shops',s.id)));r.append(iconLetter(doc,s.shopName||s.botUsername||'D'),el(doc,'span','uw-platform-list-row__copy'),badge(doc,statusLabel(s.status),statusTone(s.status)));const cp=r.children?.[1];cp?.append?.(el(doc,'strong','',s.shopName||s.botUsername||s.publicCode||'Do‘kon'),el(doc,'small','',`${s.tariffName||'Tarifsiz'} · ${subscriptionExpiryLabel(s)}`));shopsCard.append(r);}}
  shopsCard.append(createButton({label:'Barcha do‘konlar',variant:'secondary',onClick:()=>onNavigate?.('/platform/shops')},doc));cards.append(shopsCard);
  const reqCard=el(doc,'section','uw-platform-card');reqCard.append(el(doc,'h2','',"Arizalar"));if(!state.requests.length)reqCard.append(el(doc,'p','uw-muted','Hali ariza yuborilmagan.'));else for(const r of state.requests.slice(0,3)){const row=el(doc,'button','uw-platform-list-row');row.type='button';row.addEventListener('click',()=>onNavigate?.(platformPath('requests',r.id)));const copy=el(doc,'span','uw-platform-list-row__copy');copy.append(el(doc,'strong','',requestKindLabel(r)),el(doc,'small','',`${r.tariffName||'Tarif'} · ${date(r.createdAt)}`));row.append(iconLetter(doc,'A'),copy,badge(doc,statusLabel(r.status),statusTone(r.status)));reqCard.append(row);}reqCard.append(createButton({label:'Arizalarni ko‘rish',variant:'secondary',onClick:()=>onNavigate?.('/platform/requests')},doc));cards.append(reqCard);wrap.append(cards);return wrap;
}

function shopsView(doc,state,onNavigate,controller,params){
  const shopId=params?.shopId||null;const shop=state.shops.find(s=>s.id===shopId)||null;const wrap=el(doc,'div','uw-platform-page');
  if(shop){const back=createButton({label:'← Do‘konlar',variant:'ghost',onClick:()=>onNavigate?.('/platform/shops')},doc);wrap.append(back,pageHeading(doc,shop.shopName||shop.botUsername||shop.publicCode||'Do‘kon',`${shop.tariffName||'Tarifsiz'} · ${statusLabel(shop.status)}`));
    const hero=el(doc,'section','uw-platform-card uw-platform-shop-detail');const top=el(doc,'div','uw-platform-shop-detail__top');const copy=el(doc,'div');copy.append(el(doc,'small','uw-muted','Joriy holat'),el(doc,'h2','',statusLabel(shop.status)),el(doc,'p','uw-muted',shop.lifecycleReason||subscriptionExpiryLabel(shop)));top.append(copy,badge(doc,statusLabel(shop.status),statusTone(shop.status)));hero.append(top);
    const stats=el(doc,'div','uw-platform-stat-grid uw-platform-stat-grid--compact');for(const [l,v] of [['Mahsulotlar',shop.productLimit?`${shop.usedProductCount}/${shop.productLimit}`:shop.usedProductCount],['Bugungi buyurtmalar',shop.ordersToday],['Jami buyurtmalar',shop.usedOrderCount],['Obuna',subscriptionExpiryLabel(shop)]]){const c=el(doc,'div','uw-platform-stat');c.append(el(doc,'small','',l),el(doc,'strong','',v));stats.append(c);}hero.append(stats);
    const actions=el(doc,'div','uw-platform-inline-actions');if(shop.botUsername){const a=el(doc,'a','uw-button uw-button--secondary',"Telegram do‘konini ochish");a.href=`https://t.me/${encodeURIComponent(shop.botUsername)}`;a.target='_blank';a.rel='noopener';actions.append(a);}actions.append(createButton({label:'Obunani boshqarish',onClick:()=>onNavigate?.(`/platform/subscriptions?shop=${encodeURIComponent(shop.id)}`)},doc));hero.append(actions);wrap.append(hero);return wrap;}
  const action=createButton({label:'+ Yangi do‘kon',onClick:()=>{controller.beginCheckout({kind:'NEW_SHOP'});onNavigate?.('/platform/subscriptions?new=1');}},doc);wrap.append(pageHeading(doc,"Do‘konlarim",state.shops.length?`${state.shops.length} ta ulangan do‘kon`:'Hozircha do‘kon yo‘q',action));
  if(!state.shops.length){wrap.append(createStatePanel({kind:'empty',title:"Do‘kon hali yo‘q",message:'Yangi do‘kon ochish uchun tarifni tanlang va ariza yuboring.',actionLabel:'Tariflarni ko‘rish',onAction:()=>onNavigate?.('/platform/subscriptions?new=1')},doc));return wrap;}
  const list=el(doc,'div','uw-platform-card-list');for(const s of state.shops){const card=el(doc,'button','uw-platform-shop-card');card.type='button';card.addEventListener('click',()=>onNavigate?.(platformPath('shops',s.id)));const title=el(doc,'div','uw-platform-shop-card__title');title.append(iconLetter(doc,s.shopName||s.botUsername||'D'),el(doc,'strong','',s.shopName||s.botUsername||s.publicCode||'Do‘kon'),badge(doc,statusLabel(s.status),statusTone(s.status)));const meta=el(doc,'div','uw-platform-shop-card__meta');meta.append(el(doc,'span','',s.tariffName||'Tarifsiz'),el(doc,'span','',subscriptionExpiryLabel(s)));card.append(title,meta);list.append(card);}wrap.append(list);return wrap;
}

function tariffSelect(doc,state,checkout,controller){const grid=el(doc,'div','uw-platform-plan-grid');for(const t of state.tariffs){const b=el(doc,'button',`uw-platform-plan-choice ${checkout?.tariffId===t.id?'is-selected':''}`);b.type='button';b.addEventListener('click',()=>controller.patchCheckout({tariffId:t.id}));b.append(el(doc,'strong','',t.name),el(doc,'span','',money(checkout?.billingPeriod==='annual'?t.price*10:t.price)),el(doc,'small','',t.productLimit==null?'Mahsulot limiti belgilanmagan':`${t.productLimit} tagacha mahsulot`));grid.append(b);}return grid;}
function paymentChoices(doc,state,checkout,controller){const box=el(doc,'div','uw-platform-payment-methods');const card=state.paymentInfo; if(card?.cardNumber&&card?.isActive!==false){const b=el(doc,'button',`uw-platform-payment-choice ${checkout?.paymentMethod==='CARD'?'is-selected':''}`);b.type='button';b.addEventListener('click',()=>controller.selectCardPayment());const copy=el(doc,'div');copy.append(el(doc,'strong','',"Karta"),el(doc,'small','',`${card.cardNumber}${card.cardHolder?` · ${card.cardHolder}`:''}`));b.append(copy);box.append(b);}for(const m of state.paymentMethods){const b=el(doc,'button',`uw-platform-payment-choice ${checkout?.paymentMethodId===m.id?'is-selected':''}`);b.type='button';b.addEventListener('click',()=>controller.selectExternalPayment(m.id));const copy=el(doc,'div');copy.append(el(doc,'strong','',m.displayName||m.methodType),el(doc,'small','',"Tashqi to‘lov sahifasi"));b.append(copy);box.append(b);}return box;}
function checkoutView(doc,state,controller,onNavigate){const c=state.checkout;if(!c)return null;const panel=el(doc,'section','uw-platform-card uw-platform-checkout-card');const head=el(doc,'div','uw-platform-checkout-head');head.append(el(doc,'div','',null),createButton({label:'Yopish',variant:'ghost',size:'sm',onClick:()=>controller.cancelCheckout()},doc));head.children?.[0]?.append?.(el(doc,'small','uw-muted',c.kind==='NEW_SHOP'?"Yangi do‘kon":"Obuna"),el(doc,'h2','',c.kind==='NEW_SHOP'?"Yangi do‘kon arizasi":c.upgradeAction==='EXTEND'?'Obunani uzaytirish':"Tarifni o‘zgartirish"));panel.append(head);
  const billing=el(doc,'div','uw-platform-segmented');for(const [v,l] of [['monthly','Oylik'],['annual','Yillik · 2 oy bepul']]){const b=el(doc,'button',c.billingPeriod===v?'is-active':'',l);b.type='button';b.addEventListener('click',()=>controller.patchCheckout({billingPeriod:v}));billing.append(b);}panel.append(billing,tariffSelect(doc,state,c,controller));
  if(c.kind==='NEW_SHOP'){const form=el(doc,'div','uw-platform-form-grid');for(const [key,label,type,placeholder] of [['shopName',"Do‘kon nomi",'text',"Masalan, FITCORE"],['ownerTelegramId','Owner Telegram ID','text','123456789'],['botName','Bot nomi (ixtiyoriy)','text','FITCORE Shop'],['botBio','Bot bio (ixtiyoriy)','text','Sport mahsulotlari do‘koni']]){const field=el(doc,'label','uw-field');field.append(el(doc,'span','',label));const input=doc.createElement(key==='botBio'?'textarea':'input');if(input.tagName==='INPUT')input.type=type;input.value=c[key]||'';input.placeholder=placeholder;input.addEventListener('input',(e)=>controller.patchCheckout({[key]:e.target?.value??input.value}));field.append(input);form.append(field);}panel.append(form);const prep=createButton({label:c.preparedRequestId?'Ariza drafti saqlandi':'To‘lov draftini tayyorlash',variant:'secondary',onClick:()=>controller.prepareNewShopDraft()},doc);panel.append(prep);if(c.paymentDeadlineAt)panel.append(el(doc,'small','uw-muted',`Draft muddati: ${dateTime(c.paymentDeadlineAt)} gacha`));}
  if(c.kind==='UPGRADE'&&c.upgradeAction==='CHANGE'&&state.changePreview?.status==='ready'&&state.changePreview.data){const p=state.changePreview.data;const prev=el(doc,'div','uw-platform-change-preview');prev.append(el(doc,'strong','',"Qolgan obuna qiymati saqlanadi"),el(doc,'span','',`Qolgan qiymat: ${money(p.remainingValue||0)} · ${Number(p.convertedDays||0)} kun yangi tarifga o‘tadi.`));panel.append(prev);}
  panel.append(el(doc,'h3','',"To‘lov usuli"),paymentChoices(doc,state,c,controller));
  const chosen=state.paymentMethods.find(m=>m.id===c.paymentMethodId);if(chosen&&safeUrl(chosen.paymentUrl)){const link=el(doc,'a','uw-platform-pay-link',"To‘lov sahifasini ochish ↗");link.href=safeUrl(chosen.paymentUrl);link.target='_blank';link.rel='noopener';link.addEventListener('click',()=>controller.patchCheckout({externalOpened:true}));panel.append(link);}
  const receipt=el(doc,'label','uw-field');receipt.append(el(doc,'span','',"Chek rasmi (ixtiyoriy)"));const file=doc.createElement('input');file.type='file';file.accept='image/jpeg,image/png,image/webp';file.addEventListener('change',(e)=>controller.patchCheckout({receiptFile:e.target?.files?.[0]||null}));receipt.append(file);panel.append(receipt);
  const consent=el(doc,'label','uw-platform-consent');const check=doc.createElement('input');check.type='checkbox';check.checked=c.consentAccepted===true;check.addEventListener('change',(e)=>controller.patchCheckout({consentAccepted:e.target?.checked===true}));consent.append(check,el(doc,'span','',"Foydalanish shartlari va Maxfiylik siyosatiga roziman."));panel.append(consent);
  if(state.checkoutError)panel.append(createStatePanel({kind:'error',title:'Ariza yuborilmadi',message:state.checkoutError.message||'Xato yuz berdi.'},doc));
  if(['submitted','claim-warning','receipt-warning'].includes(state.checkoutStatus))panel.append(createStatePanel({kind:state.checkoutStatus==='submitted'?'success':'warning',title:state.checkoutStatus==='submitted'?'Ariza yuborildi':'Ariza yaratildi',message:state.checkoutStatus==='submitted'?"Holatini Arizalar bo‘limida kuzating.":'To‘lov vaqtini qayta tasdiqlash kerak bo‘lishi mumkin.',actionLabel:'Arizalarni ko‘rish',onAction:()=>onNavigate?.('/platform/requests')},doc));
  else panel.append(createButton({label:state.checkoutStatus==='submitting'?'Yuborilmoqda…':"To‘lovni tasdiqlash va arizani yuborish",disabled:state.checkoutStatus==='submitting',onClick:()=>controller.submitCheckout()},doc));if(['claim-warning','receipt-warning'].includes(state.checkoutStatus))panel.append(createButton({label:'Tasdiqlashni qayta urinish',onClick:()=>controller.submitCheckout()},doc));return panel;}

function subscriptionsView(doc,state,onNavigate,controller,search=''){
  const wrap=el(doc,'div','uw-platform-page');const params=new URLSearchParams(search||'');const shopId=params.get('shop')||state.selectedShopId;
  const action=createButton({label:'+ Yangi do‘kon',onClick:()=>controller.beginCheckout({kind:'NEW_SHOP'})},doc);wrap.append(pageHeading(doc,'Obunalar','Tarif, obuna muddati va serverdagi to‘lov tarixini boshqaring.',action));
  if(state.shops.length){const select=el(doc,'div','uw-platform-shop-switcher');for(const s of state.shops){const b=el(doc,'button',s.id===shopId?'is-active':'',s.shopName||s.botUsername||s.publicCode);b.type='button';b.addEventListener('click',()=>{controller.loadHistory(s.id);onNavigate?.(`/platform/subscriptions?shop=${encodeURIComponent(s.id)}`);});select.append(b);}wrap.append(select);const shop=state.shops.find(s=>s.id===shopId)||state.shops[0];if(shop){const card=el(doc,'section','uw-platform-card');const top=el(doc,'div','uw-platform-sub-current');const copy=el(doc,'div');copy.append(el(doc,'small','uw-muted','Joriy tarif'),el(doc,'h2','',shop.tariffName||'Tarifsiz'),el(doc,'p','uw-muted',subscriptionExpiryLabel(shop)));const acts=el(doc,'div','uw-platform-inline-actions');acts.append(createButton({label:'Uzaytirish',variant:'secondary',onClick:()=>controller.beginCheckout({kind:'UPGRADE',shopId:shop.id,tariffId:shop.tariffId||state.tariffs[0]?.id,upgradeAction:'EXTEND'})},doc),createButton({label:"Tarifni o‘zgartirish",onClick:()=>controller.beginCheckout({kind:'UPGRADE',shopId:shop.id,tariffId:state.tariffs.find(t=>t.id!==shop.tariffId)?.id||shop.tariffId||state.tariffs[0]?.id,upgradeAction:'CHANGE'})},doc));top.append(copy,acts);card.append(top);wrap.append(card);const hist=el(doc,'section','uw-platform-card');hist.append(el(doc,'h2','',"To‘lovlar tarixi"));if(state.historyStatus==='loading')hist.append(createStatePanel({kind:'loading',title:'Tarix yuklanmoqda',message:'Serverdagi obuna tarixi olinmoqda.'},doc));else if(state.historyStatus==='error')hist.append(createStatePanel({kind:'error',title:'Tarix yuklanmadi',message:'Qayta urinib ko‘ring.',actionLabel:'Qayta urinish',onAction:()=>controller.loadHistory(shop.id)},doc));else if(!state.history.length)hist.append(createStatePanel({kind:'empty',title:'Hali to‘lov yo‘q',message:'Tasdiqlangan obuna to‘lovlari shu yerda ko‘rinadi.'},doc));else for(const h of state.history){const row=el(doc,'div','uw-platform-history-row');const copy=el(doc,'div');copy.append(el(doc,'strong','',money(h.purchasedAmount)),el(doc,'small','',`${h.newTariffName||'Tarif'} · ${h.billingPeriod==='ANNUAL'?'Yillik':'Oylik'} · ${date(h.createdAt)}`));row.append(copy,badge(doc,'To‘langan','success'));hist.append(row);}wrap.append(hist);}}
  else {const no=el(doc,'section','uw-platform-card');no.append(el(doc,'h2','',"Birinchi do‘kon uchun tarif"),el(doc,'p','uw-muted',"Tarifni tanlang, so‘ng to‘lov arizasini yuboring."),tariffSelect(doc,state,state.checkout||{tariffId:null,billingPeriod:'monthly'},controller));wrap.append(no);}
  const checkout=checkoutView(doc,state,controller,onNavigate);if(checkout)wrap.prepend?wrap.prepend(checkout):wrap.children.unshift(checkout);return wrap;
}

function requestsView(doc,state,onNavigate,controller,params){const wrap=el(doc,'div','uw-platform-page');const requestId=params?.requestId||null;const req=state.requests.find(r=>r.id===requestId)||null;if(req){const back=createButton({label:'← Arizalar',variant:'ghost',onClick:()=>onNavigate?.('/platform/requests')},doc);wrap.append(back,pageHeading(doc,requestKindLabel(req),`${req.tariffName||'Tarif'} · ${statusLabel(req.status)}`));const card=el(doc,'section','uw-platform-card');const grid=el(doc,'div','uw-platform-detail-grid');for(const [l,v] of [['Holat',statusLabel(req.status)],['Tarif',req.tariffName||'—'],['Summa',money(req.tariffPrice)],['Davr',req.billingPeriod==='ANNUAL'?'Yillik':'Oylik'],['Yaratildi',dateTime(req.createdAt)],['To‘lov usuli',req.paymentMethod||'Hali tanlanmagan']]){const d=el(doc,'div');d.append(el(doc,'small','',l),el(doc,'strong','',v));grid.append(d);}card.append(grid);if(req.status==='REJECTED'&&req.rejectReason)card.append(createStatePanel({kind:'error',title:'Ariza rad etilgan',message:req.rejectReason},doc));if(req.kind==='NEW_SHOP'&&req.status==='NEW'&&!req.paymentClaimedAt){card.append(createButton({label:"To‘lovni davom ettirish",onClick:()=>{controller.resumeRequest(req.id);onNavigate?.('/platform/subscriptions?new=1');}},doc));}if(req.status==='NEW'&&req.receiptRequestedAt&&!req.hasReceipt){const label=el(doc,'label','uw-field');label.append(el(doc,'span','',"Administrator chek so‘radi"));const file=doc.createElement('input');file.type='file';file.accept='image/jpeg,image/png,image/webp';file.addEventListener('change',(e)=>{const f=e.target?.files?.[0];if(f)controller.attachRequestReceipt(req.id,f);});label.append(file);card.append(label);}wrap.append(card);const timeline=el(doc,'section','uw-platform-card');timeline.append(el(doc,'h2','',"Ariza tarixi"));if(state.requestHistoryStatus==='loading')timeline.append(createStatePanel({kind:'loading',title:'Tarix yuklanmoqda',message:'Ariza bosqichlari olinmoqda.'},doc));else if(!state.requestHistory.length)timeline.append(el(doc,'p','uw-muted','Tarix yozuvlari hozircha yo‘q.'));else{const list=el(doc,'div','uw-platform-timeline');for(const h of state.requestHistory){const item=el(doc,'div','uw-platform-timeline__item');item.append(el(doc,'span','uw-platform-timeline__dot'),el(doc,'div','uw-platform-timeline__copy'));item.children?.[1]?.append?.(el(doc,'strong','',String(h.eventType||'EVENT').replaceAll('_',' ')),el(doc,'small','',`${dateTime(h.createdAt)} · ${h.actorType||'SYSTEM'}`));list.append(item);}timeline.append(list);}wrap.append(timeline);return wrap;}
  wrap.append(pageHeading(doc,'Arizalarim','Yangi do‘kon, uzaytirish va tarif almashtirish so‘rovlarining serverdagi holati.'));if(!state.requests.length){wrap.append(createStatePanel({kind:'empty',title:'Hali ariza yo‘q',message:'Yangi do‘kon yoki obuna amali yuborilganda shu yerda ko‘rinadi.',actionLabel:'Obunalarni ochish',onAction:()=>onNavigate?.('/platform/subscriptions')},doc));return wrap;}const list=el(doc,'div','uw-platform-card-list');for(const r of state.requests){const row=el(doc,'button','uw-platform-request-row');row.type='button';row.addEventListener('click',()=>onNavigate?.(platformPath('requests',r.id)));const copy=el(doc,'div');copy.append(el(doc,'strong','',requestKindLabel(r)),el(doc,'small','',`${r.tariffName||'Tarif'} · ${money(r.tariffPrice)} · ${date(r.createdAt)}`));row.append(copy,badge(doc,statusLabel(r.status),statusTone(r.status)));list.append(row);}wrap.append(list);return wrap;}

function supportView(doc,state,onNavigate,controller,params){const wrap=el(doc,'div','uw-platform-page');const ticketId=params?.ticketId?Number(params.ticketId):null;const ticket=state.tickets.find(t=>Number(t.id)===ticketId)||null;if(ticket){const back=createButton({label:'← Yordam',variant:'ghost',onClick:()=>onNavigate?.('/platform/support')},doc);wrap.append(back,pageHeading(doc,`Murojaat #${ticket.id}`,`${ticket.type==='BUG_REPORT'?'Muammo':'Support'} · ${statusLabel(ticket.status)}`));const thread=el(doc,'section','uw-platform-card uw-platform-thread');if(state.supportStatus==='loading')thread.append(createStatePanel({kind:'loading',title:'Xabarlar yuklanmoqda',message:'Murojaat tarixi olinmoqda.'},doc));else for(const m of state.messages){const msg=el(doc,'div',`uw-platform-message ${m.sender==='ADMIN'?'is-admin':'is-user'}`);msg.append(el(doc,'small','',m.sender==='ADMIN'?'UStorE jamoasi':'Siz'),el(doc,'p','',m.body||''),el(doc,'time','',dateTime(m.createdAt)));if(m.attachmentUrl){const a=el(doc,'a','',"Biriktirma ↗");a.href=safeUrl(m.attachmentUrl)||'#';a.target='_blank';a.rel='noopener';msg.append(a);}thread.append(msg);}if(ticket.status!=='CLOSED'){const form=el(doc,'form','uw-platform-reply');const input=doc.createElement('textarea');input.placeholder='Xabar yozing…';input.setAttribute('aria-label','Support xabari');const send=createButton({label:'Yuborish'},doc);form.append(input,send);form.addEventListener('submit',async(e)=>{e.preventDefault?.();const body=String(input.value||'').trim();if(!body)return;const r=await controller.sendSupportMessage(ticket.id,body);if(r.ok)input.value='';});thread.append(form,createButton({label:'Murojaatni yopish',variant:'ghost',onClick:()=>controller.closeTicket(ticket.id)},doc));}wrap.append(thread);return wrap;}
  const newBtn=createButton({label:'+ Murojaat yozish',onClick:()=>{const form=globalThis.document?.getElementById?.('uw-platform-new-ticket');scrollElementIntoView(form, { block:'start' });}},doc);wrap.append(pageHeading(doc,'Yordam','Jamoamiz bilan yozishing yoki muammo haqida xabar yuborishing mumkin.',newBtn));const form=el(doc,'form','uw-platform-card uw-platform-support-form');form.id='uw-platform-new-ticket';const type=doc.createElement('select');type.setAttribute('aria-label','Murojaat turi');for(const [v,l] of [['SUPPORT','Qo‘llab-quvvatlash'],['BUG_REPORT','Muammo haqida xabar']]){const o=doc.createElement('option');o.value=v;o.textContent=l;type.append(o);}const subject=doc.createElement('input');subject.placeholder='Mavzu (ixtiyoriy)';subject.setAttribute('aria-label','Murojaat mavzusi');const message=doc.createElement('textarea');message.placeholder='Savol yoki muammoni batafsil yozing…';message.setAttribute('aria-label','Murojaat matni');const file=doc.createElement('input');file.type='file';file.accept='image/jpeg,image/png,image/webp';file.setAttribute('aria-label','Rasm biriktirish');form.append(type,subject,message,file,createButton({label:'Yuborish'},doc));form.addEventListener('submit',async(e)=>{e.preventDefault?.();const r=await controller.createTicket({type:type.value,message:message.value,subject:subject.value,pageContext:'premium-web',file:file.files?.[0]||null});if(r.ok){message.value='';subject.value='';file.value='';}});wrap.append(form);
  const tickets=el(doc,'section','uw-platform-card');tickets.append(el(doc,'h2','',"Mening murojaatlarim"));if(state.supportStatus==='loading')tickets.append(createStatePanel({kind:'loading',title:'Murojaatlar yuklanmoqda',message:'Serverdan ma’lumot olinmoqda.'},doc));else if(state.supportStatus==='error')tickets.append(createStatePanel({kind:'error',title:'Murojaatlar yuklanmadi',message:state.supportError?.message||'Xato yuz berdi.',actionLabel:'Qayta urinish',onAction:()=>controller.loadSupport()},doc));else if(!state.tickets.length)tickets.append(el(doc,'p','uw-muted','Hali murojaat yo‘q.'));else for(const t of state.tickets){const row=el(doc,'button','uw-platform-request-row');row.type='button';row.addEventListener('click',()=>onNavigate?.(platformPath('support',t.id)));const copy=el(doc,'div');copy.append(el(doc,'strong','',t.subject||`${t.type==='BUG_REPORT'?'Muammo':'Support'} #${t.id}`),el(doc,'small','',dateTime(t.createdAt)));row.append(copy,badge(doc,statusLabel(t.status),statusTone(t.status)));tickets.append(row);}wrap.append(tickets);return wrap;}

function profileView(doc,state,controller,onSignedOut){const wrap=el(doc,'div','uw-platform-page');wrap.append(pageHeading(doc,'Profil','Markaziy UStorE akkaunti va platformadagi holatingiz.'));const card=el(doc,'section','uw-platform-card uw-platform-profile-card');card.append(iconLetter(doc,state.actor?.displayName||'U'));const copy=el(doc,'div');copy.append(el(doc,'h2','',state.actor?.displayName||'UStorE foydalanuvchi'),el(doc,'p','uw-muted',state.actor?.telegramLinked?'Telegram akkaunti bog‘langan':'Telegram holati noma’lum'),el(doc,'small','uw-muted',`Account ID: ${state.actor?.accountId||'—'}`));card.append(copy,badge(doc,state.isSuperAdmin?'SUPER ADMIN':'USER',state.isSuperAdmin?'warning':'neutral'));wrap.append(card);const stats=el(doc,'div','uw-platform-stat-grid');for(const [l,v] of [["Do‘konlar",state.shops.length],['Faol obunalar',state.shops.filter(s=>s.status==='ACTIVE').length],['Arizalar',state.requests.length]]){const c=el(doc,'div','uw-platform-stat');c.append(el(doc,'small','',l),el(doc,'strong','',v));stats.append(c);}wrap.append(stats);const security=el(doc,'section','uw-platform-card');security.append(el(doc,'h2','',"Akkaunt xavfsizligi"),el(doc,'p','uw-muted','Web sessiya markaziy UStorE autentifikatsiyasi orqali boshqariladi. Profil sahifasi shop-admin sessiyasini o‘zgartirmaydi.'));const logout=createButton({label:'Akkauntdan chiqish',variant:'danger',onClick:async()=>{const r=await controller.signOut();if(r.ok)onSignedOut?.();}},doc);security.append(logout);wrap.append(security);return wrap;}

export function createPlatformPortalView({controller,state=controller?.getState?.()||{},section='app',params={},search='',onNavigate,onSignedOut}={},documentRef){const doc=getDocument(documentRef);if(!controller)throw new TypeError('controller kerak');const root=el(doc,'div','uw-platform-portal uw-root');root.dataset.feature='platform-portal';root.append(portalHeader(doc,state,{onNavigate,onLogout:async()=>{const r=await controller.signOut();if(r.ok)onSignedOut?.();}}));const body=el(doc,'div','uw-platform-portal__body');body.append(portalNav(doc,section,onNavigate,state));const main=el(doc,'main','uw-platform-portal__main');main.id='uw-main-content';const statePanel=statePanelFor(doc,state,()=>controller.load());if(statePanel)main.append(statePanel);else{if(state.notice){main.append(createStatePanel({kind:state.notice.kind,title:state.notice.kind==='success'?'Bajarildi':'Eslatma',message:state.notice.message},doc));}
  if(section==='shops')main.append(shopsView(doc,state,onNavigate,controller,params));else if(section==='subscriptions')main.append(subscriptionsView(doc,state,onNavigate,controller,search));else if(section==='requests')main.append(requestsView(doc,state,onNavigate,controller,params));else if(section==='support')main.append(supportView(doc,state,onNavigate,controller,params));else if(section==='profile')main.append(profileView(doc,state,controller,onSignedOut));else main.append(overviewView(doc,state,onNavigate,controller));}
  body.append(main);root.append(body);return {element:root};}
